PRINT '' PRINT '*** using tcg_db'
GO
USE [tcg_db]
GO

PRINT '' PRINT '' PRINT 'Adding values to Tables in tcg_db'

PRINT '*** adding to Role Table ***'
GO
INSERT INTO [dbo].[Role]
	([RoleID],[Description])
VALUES
	('Admin','This user can create an entry for new cards, boosters,
		artist, alternate arts, abilitys, element types, moves, pokedex, pokemon rules,
		stages, stage evolutions, or pokemon evolutions'),
	
	('General','This is the standard user can not create new cards, boosters,
		artist, alternate arts, abilitys, element types, moves, pokedex, pokemon rules,
		stages, stage evolutions, or pokemon evolutions')
GO

PRINT '*** adding to Users Table ***'
GO
INSERT INTO [dbo].[Users]
	([GivenName],[Surname],[Email])
VALUES
	('john','stewart','john@mail.com'),
	('ceedee','lamb','lamb@mail.com'),
	('daniel','jones','daniel@mail.com'),
	('harrison','mevis','mevis@mail.com'),
	('tom','ford','tom@mail.com')
GO

PRINT '*** adding to UserRole Table ***'
GO
INSERT INTO [dbo].[UserRole]
	([RoleID],[UserID])
VALUES
	('Admin',10000),
	('General',10001),
	('General',10002),
	('General',10003),
	('General',10004)
GO

PRINT '*** adding to AlternateArt Table ***'
GO
INSERT INTO [dbo].[AlternateArt]
	([AlternateArtID],[Description])
VALUES
	('none','standard card'),
	('jumbo','oversized cards that come in special boxes.'),
	('reverse holo','same as a standard card but the background has foil rather than the picture.'),
	('reverse holo pokeball','same as reverse holo but has pokeballs on the foil.'),
	('reverse holo master ball','same as reverse holo but has master balls on the foil.')
GO

PRINT '*** adding to Ability Table ***'
GO
INSERT INTO [dbo].[Ability]
	([AbilityID],[AbilityType],[Description])
VALUES
('none','none','none'),
('rain dance','pokemon power','As often as you like during your turn (before your attack), you may attach 1 Water Energy card to 1 of your Water Pokémon. (This doesn''t use up your 1 Energy card attachment for the turn.) This power can''t be used if Blastoise is Asleep, Confused, or Paralyzed.'),
('strikes back','pokemon power','Whenever your opponent''s attack damages Machamp (even if Machamp is Knocked Out), this power does 10 damage to the attacking Pokémon. (Don''t apply Weakness and Resistance.) This power can''t be used if Machamp is Asleep, Confused, or Paralyzed when your opponent attacks.'),
('energy trans','pokemon power','As often as you like during your turn (before your attack), you may take 1 Grass Energy card attached to 1 of your Pokémon and attach it to a different one. This power can''t be used if your pokemon is Asleep, Confused, or Paralyzed.'),
('invisible wall','pokemon power','Whenever an attack (including your own) does 30 or more damage to Mr. Mime (after applying Weakness and Resistance), prevent that damage. (Any other effects of attacks still happen.) This power can''t be used if Mr. Mime is Asleep, Confused, or Paralyzed.'),
('thick skinned','pokemon power','Snorlax can''t become Asleep, Confused, Paralyzed, or Poisoned. This power can''t be used if Snorlax is already Asleep, Confused, or Paralyzed.'),
('shift','pokemon power','Once during your turn (before your attack), you may change the type of Venomoth to the type of any other Pokémon in play other than Colorless. This power can''t be used if Venomoth is Asleep, Confused, or Paralyzed.'),
('power saver','ability','This Pokemon can''t attack unless you have 4 or more Team Rocket''s in play.')
GO

PRINT '*** adding to ElementType Table ***'
GO
INSERT INTO [dbo].[ElementType]
	([ElementTypeID],[Description])
VALUES
	('colorless',''),
	('fire',''),
	('water',''),
	('grass',''),
	('electric',''),
	('ice',''),
	('fighting',''),
	('poison',''),
	('ground',''),
	('flying',''),
	('psychic',''),
	('bug',''),
	('rock',''),
	('ghost',''),
	('dragon',''),
	('dark',''),
	('steel',''),
	('fairy','')
GO

PRINT '*** adding to CollectionType Table ***'
GO
INSERT INTO [dbo].[CollectionType]
	([CollectionTypeID],[Description],[MaxSize])
VALUES
	('General','',100),
	('Wishlist','',100),
	('Favorites','',100),
	('Deck','',60)
GO


PRINT '*** adding to PokemonRule Table ***'
GO
INSERT INTO [dbo].[PokemonRule]
	([PokemonRuleID],[Description])
VALUES
	('Pokemon-EX','When a Pokemon-EX has been Knocked Out, your opponent takes 2 prize cards.'),
	('Mega Evolution','When 1 of your Pokemon becomes a Mega Evolution Pokemon, your turn ends.'),
	('Primal Reversion','When 1 of your Pokemon becomes primal your turn ends.'),
	('BREAK','Your Pokemon retains the attacks, abilities, weakness, resistance, and retreat cost of its previous evolution.'),
	('Pokemon-GX','When your Pokemon-GX is knocked out, your opponent takes 2 Prize cards.'),
	('TAG TEAM Pokemon-GX','When you TAG TEAM is knocked out, your opponenet takes 3 Prize Cards.'),
	('Prism Star','You can''t have more than 1 prism card with the same name in your deck. If a prism card would go to the discard pile, put it in the Lost Zone instead.'),
	('Pokemon V','When your Pokemon V is knocked out, your opponent takes 2 Prize Cards.'),
	('Pokemon VMAX','When your Pokemon VMAX is knocked out, your opponent takes 3 Prize Cards.'),
	('Pokemon V-UNION','When your Pokemon V-UNION is knocked out, your opponent takes 3 Prize Cards.'),
	('Pokemon VSTAR','When your Pokemon VSTAR is knocked out, your opponent takes 2 Prize Cards.'),
	('Radiant Pokemon','You can''t have more than 1 radiant pokemon in your deck.')
GO 


PRINT '*** adding to Move Table ***'
GO
INSERT INTO [dbo].[Move]
	([MoveID],[Damage],[Description])
VALUES
	('test',0,'This is a test move with no cost'),
	('shadow bind',150,'During your opponent''s next turn, the Defending Pokemon can''t retreat.'),
	('merciless blade',110,'If your opponent''s active pokemon already has any damage counters on it, this attack does 100 damage.'),
	('erasure ball',160,'You may discard up to 2 Energy from your Benched Pokemon. This attack does 60 more damage for each card you discarded in this way.')
GO

PRINT '*** adding to MoveCost ***'
GO
INSERT INTO [dbo].[MoveCost]
	([MoveID],[ElementTypeID],[Quantity])
VALUES
	('shadow bind','psychic',2),
	('shadow bind','colorless',1),
	('merciless blade','dark',2),
	('merciless blade','colorless',2),
	('merciless blade','psychic',2),
	('erasure ball','psychic',2),
	('erasure ball','colorless',1)
GO

PRINT '*** adding to Artist Table ***'
GO
INSERT INTO [dbo].[Artist]
	([GivenName],[Surname])
VALUES
	('5ban','graphics'),
	('0313',''),
	('2003 pikachu','project'),
	('2004 pikachu','project'),
	('2005 pikachu','project'),
	('2006 pikachu','project'),
	('2009 pikachu','project'),
	('2014 pikachu','project'),
	('2017 pikachu','project'),
	('2018 pikachu','project'),
	('2019 pikachu','project'),
	('2020 pikachu','project'),
	('ack cg','works'),
	('acorviart',''),
	('adidas enjin','project'),
	('ai','kurihara'),
	('aimi','tomita'),
	('akagi',''),
	('akino','fukuji'),
	('akira','egawa'),
	('akira','komayama'),
	('aky cg','works'),
	('aliya','chen'),
	('amelicart',''),
	('anderson',''),
	('anesaki','dynamic'),
	('aoki',''),
	('apios',''),
	('arai','kiriko'),
	('asako','ito'),
	('aspara',''),
	('asuka','iwashita'),
	('atsuko','nishida'),
	('atsuko','ujiie'),
	('atsushi','furusawa'),
	('atsuya','uki'),
	('avec','yoko'),
	('ayaka','yoshida'),
	('ayako','ozaki'),
	('aya','kusube'),
	('ayoka','yoshida'),
	('ayumi','odashima'),
	('benimaru','itoh'),
	('beruburi',''),
	('big mama','tagawa'),
	('booota',''),
	('buchi',''),
	('bun','toujo'),
	('burari',''),
	('chibi',''),
	('christopher','rush'),
	('cochi8i',''),
	('cona','nitanda'),
	('conceptlab',''),
	('craig','turvey'),
	('cr cg','gangs'),
	('d.a.g','inc.'),
	('daisuke','ito'),
	('daisuke','iwamoto'),
	('daisuke','ochiai'),
	('danciao',''),
	('demizuposuka',''),
	('dom',''),
	('dr.ooyama',''),
	('dsuke',''),
	('ebila',''),
	('emi','ando'),
	('emi','miwa'),
	('emi','yoshida'),
	('en','morikura'),
	('eri','kamei'),
	('eri','yamaki'),
	('eske','yoshinob'),
	('etsuya','hattori'),
	('felicia','chen'),
	('framestore',''),
	('fujimoto','gold'),
	('fumie','kittaka'),
	('fuzichoco',''),
	('gakuji','nomoto'),
	('game freak','inc.'),
	('gapao',''),
	('gemi',''),
	('gidora',''),
	('ginga',''),
	('gogotake',''),
	('gosho','aoyama'),
	('gossan',''),
	('goto','minori'),
	('hagiya','kaoru'),
	('hajime','kusajima'),
	('hanabushi',''),
	('hanako',''),
	('haru','akasaka'),
	('haruko','ichikawa'),
	('hasegawa','saki'),
	('hasuno',''),
	('hatachu',''),
	('hataya',''),
	('heisuke','kitazawa'),
	('hico','kim'),
	('hideaki','hakozaki'),
	('hideki','ishikawa'),
	('hideki','kazama'),
	('hideyuki','nakajima'),
	('hiiroki','asanuma'),
	('hikaru','koike'),
	('hiranobu','uoshida'),
	('hiroaki','ito'),
	('hiroki','asanuma'),
	('hiroki','fuchino'),
	('hiromichi','sugiyama'),
	('hiron',''),
	('hironobu','yoshida'),
	('hirotaka','marufuji'),
	('hiroyuki','yamamoto'),
	('hisao','nakamura'),
	('hitoshi','ariga'),
	('hizuki','misono'),
	('hncl',''),
	('hoshino','kuro'),
	('huang tzu','en'),
	('hyogonosuke',''),
	('ikeda','saki'),
	('imakuni',''),
	('imakunki',''),
	('imoniii',''),
	('inose','yukie'),
	('iori','suzuki'),
	('ito','kyoko'),
	('ito','kyoto'),
	('iwaiya',''),
	('iwamoto05',''),
	('izucch',''),
	('james','turner'),
	('jerky',''),
	('jiro','sasumo'),
	('jiro','sasuno'),
	('julie','hang'),
	('jumpei','akasaka'),
	('jungo','suzuki'),
	('junsei','kuninobu'),
	('k.','hoshiba'),
	('k.','utsunomiya'),
	('kadama',''),
	('kagemaru','himeno'),
	('kai','ishikawa'),
	('kamome','shirahama'),
	('kamonabe',''),
	('kanahei',''),
	('kanako','eo'),
	('kanami','ogata'),
	('kantaro',''),
	('kariya',''),
	('kasumi','matsuda'),
	('katsunori','sato'),
	('katsura','tabata'),
	('kawayoo',''),
	('kazuaki','aihara'),
	('kazuhiko','nishihara'),
	('kazuki','minami'),
	('kazuma','koda'),
	('kazumasa','yasukuni'),
	('kazuo','yazawa'),
	('kazuyuki','kano'),
	('kedamahadaitai','yawarakai'),
	('kei','hoshinba'),
	('keiichiro','ito'),
	('keiji','kinebuchi'),
	('keiko','fukuyama'),
	('keiko','moritsugu'),
	('keisin',''),
	('keita','komatsuya'),
	('keita','takahashi'),
	('ken','ikuji'),
	('kenkichi','toyama'),
	('ken','sugimori'),
	('kent','kanetsuna'),
	('kg-2000',''),
	('k','hoshiba'),
	('kimiya','masago'),
	('kinu','nishimura'),
	('kirisaki',''),
	('kiyotaka','oshiyama'),
	('kodama',''),
	('koji','nakata'),
	('kouji','tajima'),
	('kouki','saitou'),
	('krgc',''),
	('kunihiko','yuyama'),
	('kurata','so'),
	('kuroimori',''),
	('kurumitsu',''),
	('kyoko','koizumi'),
	('kyoko','umemoto'),
	('kyupiyama',''),
	('lee','hyunjung'),
	('lee','mina'),
	('ligton',''),
	('linne',''),
	('m.','akiyama'),
	('mahou',''),
	('maiko','fujiwara'),
	('makato','mizobuchi'),
	('makoto','imai'),
	('makoto','mizobuchi'),
	('makura','tami'),
	('mame','akimaru'),
	('mana','ibe'),
	('marina','chikazawa'),
	('masa',''),
	('masahiko','ishii'),
	('masakazu','fukuda'),
	('masako','tomii'),
	('masako','yamashita'),
	('mashu',''),
	('maskazu','fukuda'),
	('matazo',''),
	('match',''),
	('matofumi','fujiwara'),
	('mazakaza','fukuda'),
	('megumi','higuchi'),
	('megumi','mizutani'),
	('mekayu',''),
	('mele',''),
	('midori','harada'),
	('miho','asada'),
	('mika','pikazo'),
	('mikiko','takeda'),
	('miki','kudo'),
	('mikio','menjo'),
	('miki','tanak'),
	('miki','tanaka'),
	('milky','isobe'),
	('minahamu',''),
	('minaminami','take'),
	('mina','nakai'),
	('minato',''),
	('mingo',''),
	('mio','muroi'),
	('miranda','branley'),
	('misaki','hashimoto'),
	('misaki','hasimoto'),
	('misa','tsutsui'),
	('mitsuhiro','arita'),
	('mizue',''),
	('mori','yuu'),
	('motofumi','fujiwara'),
	('mousho',''),
	('mpc','film'),
	('mt.','tbt'),
	('mugenup',''),
	('mugi','hamada'),
	('n-design','inc.'),
	('nabana','kensaku'),
	('nabatame','kazutaka'),
	('nagano',''),
	('nagimiso',''),
	('nagomi','nijo'),
	('nakamura','ippan'),
	('nakano','satoshi'),
	('nakaoka',''),
	('naoki','saito'),
	('naoyo','kimura'),
	('narano',''),
	('narumi','sato'),
	('natsuko shinji','ete'),
	('natsumi','miyanose'),
	('natsumi','yoshida'),
	('natsumi','yoshisda'),
	('nc','empire'),
	('n design','inc.'),
	('nelnal',''),
	('nisimono',''),
	('nisota','niso'),
	('noboyuki','hobu'),
	('nobuhiro','imagawa'),
	('nobuyuki','fujimoto'),
	('nobuyuki','habu'),
	('noriko','hotta'),
	('noriko','takaya'),
	('noriko','uono'),
	('nousawa','mochipuyo'),
	('nurikabe',''),
	('okacheke',''),
	('okayamatakatoshi',''),
	('oku',''),
	('okubo',''),
	('ooyama',''),
	('orbitallink','inc.'),
	('orca',''),
	('osare',''),
	('oswaldo','kato'),
	('otumami',''),
	('ounishi',''),
	('pani','kobayashi'),
	('pikamania',''),
	('planeta',''),
	('planeta','hiiragi'),
	('planeta','igarashi'),
	('planeta','mochizuiki'),
	('planeta','mochizuki'),
	('planeta','otani'),
	('planeta','tsuji'),
	('planeta','yamashita'),
	('po-suzuki',''),
	('pokemon get','tv'),
	('pokemon','rumble'),
	('q-rais',''),
	('raita','kazama'),
	('reiko','tanoue'),
	('rend',''),
	('reospikee',''),
	('rianti','hidayat'),
	('rika',''),
	('rina',''),
	('rond',''),
	('ryoma','uratsuka'),
	('ryota','muramasa'),
	('ryota','murayama'),
	('ryota','saito'),
	('ryo','ueda'),
	('ryuta','fuse'),
	('ryuta','kusumi'),
	('saboteri',''),
	('sachiko','adachi'),
	('sachiko','eba'),
	('sachi','matoba'),
	('sadaji',''),
	('saino','misaki'),
	('saki','hayashiro'),
	('sakiko','maeda'),
	('saki','yahashiro'),
	('sanosuke','sakuma'),
	('satoma',''),
	('satoshi','nakai'),
	('satoshi','ohta'),
	('satoshi','shirai'),
	('satoshi','yamamoto'),
	('sayaka','maruyama'),
	('saya','tsuruta'),
	('sayuri','ichiishi'),
	('scav',''),
	('sekio',''),
	('shiburingaru',''),
	('shibuzoh.',''),
	('shigenori','negishi'),
	('shimaris','yukichi'),
	('shimeris','yukichi'),
	('shin-ichi','yoshida'),
	('shin-ichi','yoshikawa'),
	('shinji','higuchi'),
	('shinji','kanda'),
	('shin','nagasawa'),
	('shinya','komatsu'),
	('shinya','mazuno'),
	('shinya','mizuno'),
	('shizurow',''),
	('shoko','nakagawa'),
	('sie','nanahara'),
	('siwama','chiaki'),
	('so-taro',''),
	('souchirou','gunjima'),
	('souichirou','gunjima'),
	('sowsow',''),
	('spike','chunsoft.'),
	('studio bora','inc'),
	('studio bora','inc.'),
	('sui',''),
	('sumiyoshi','kitzuki'),
	('sumiyoshi','kizuki'),
	('susumu','maeya'),
	('suwama','chiaki'),
	('svlt',''),
	('t.','honda'),
	('taiga','kasai'),
	('taiga','kayama'),
	('taira','akitsu'),
	('takabon',''),
	('takahiro','yamashita'),
	('takao','unno'),
	('takashi','shiraishi'),
	('takashi','yamaguchi'),
	('take',''),
	('takeshia','nakamura'),
	('takeshi','nakamura'),
	('takumi','akabane'),
	('takumi','wada'),
	('takuyoa',''),
	('teeziro',''),
	('tekashi','shiraishi'),
	('terada','tera'),
	('tetsu','kayama'),
	('tetsuo','hara'),
	('tetsuo','yajima'),
	('tetsuya','koizumi'),
	('pokemon company','art team'),
	('tika','matsuno'),
	('tika','matusno'),
	('toi8',''),
	('tokichan',''),
	('tokiya',''),
	('tokumi','akabane'),
	('tomiyasu','daiki'),
	('tomoaki','imakuni'),
	('tomohiro','kitakaze'),
	('tomokazu','komiya'),
	('tomoko','wakai'),
	('tomomi','kaneko'),
	('tomomi','ozaki'),
	('tomomo','ozaki'),
	('tomowaka',''),
	('tonji','matsuno'),
	('tono',''),
	('toriyufu',''),
	('toshinao','aoki'),
	('toyste',''),
	('toyste','beach'),
	('tsuyoshi','nagano'),
	('uninori',''),
	('usgmen',''),
	('uta',''),
	('wataru','kawahara'),
	('whisker',''),
	('wintr','wandr'),
	('y.','fujishima'),
	('yamazaki','rei'),
	('yano','keiji'),
	('yashiro','nanaco'),
	('yasuda','shuhei'),
	('yasuki','watanabe'),
	('yoichi','katabe'),
	('yoko','hishida'),
	('yoriuki','ikegami'),
	('yoriyuki','ikegami'),
	('yoshimi','miyoshi'),
	('yoshinobu','saito'),
	('yoshioka',''),
	('yosuke da','silva'),
	('you','iribi'),
	('yousuke','hirata'),
	('yuichi','sawayama'),
	('yuka','morii'),
	('yuka','tanaka'),
	('yukihiro','tada'),
	('yukiko','baba'),
	('yumi',''),
	('yu','nagaba'),
	('yuriko','akase'),
	('yuri','umemura'),
	('yusuke','ishikawa'),
	('yusuke','kozaki'),
	('yusuke','ohmura'),
	('yusuke','shimada'),
	('yuu',''),
	('yuuki','kawamura'),
	('yuu','nishida'),
	('yuya','oka'),
	('zig',''),
	('zu-ka','')
GO

PRINT '*** adding to Booster Table ***'
GO
INSERT INTO [dbo].[Booster]
	([BoosterID],[Series],[ReleaseDate],[Abbreviation])
VALUES
	('Base Set','Original Series','1999-01-09','bs'),
	('Jungle','Original Series','1999-06-16','ju'),
	('Fossil','Original Series','1999-10-10','fo'),
	('Base Set 2','Original Series','2000-02-24','b2'),
	('Team Rocket','Original Series','2000-04-24','tr'),
	('Gym Heroes','Original Series','2000-08-14','g1'),
	('Gym Challenge','Original Series','2000-10-16','g2'),
	('Neo Genesis','Neo Series','2000-12-16','n1'),
	('Neo Discovery','Neo Series','2001-06-01','n2'),
	('Neo Revelation','Neo Series','2001-09-21','n3'),
	('Neo Destiny','Neo Series','2002-02-28','n4'),
	('Legendary Collection','Legendary Collection','2002-05-24','lc'),
	('Expedition Base Set','e-Card','2002-09-15','ex'),
	('Aquapolis','e-Card','2003-01-15','aq'),
	('Skyridge','e-Card','2003-05-12','sk'),
	('Ruby & Sapphire','Ex','2003-07-18','rs'),
	('Sandstorm','Ex','2003-09-18','ss'),
	('Dragon','Ex','2003-11-24','dr'),
	('Team Magma vs Team Aqua','Ex','2004-03-15','ma'),
	('Hidden Legends','Ex','2004-07-14','hl'),
	('FireRed & LeafGreen','Ex','2004-08-30','rg'),
	('Team Rocket Returns','Ex','2004-11-08','trr'),
	('Deoxys','Ex','2005-02-14','dx'),
	('Emerald','Ex','2005-05-09','em'),
	('Unseen Forces','Ex','2005-08-22','uf'),
	('Delta Species','Ex','2005-10-31','ds'),
	('Legend Maker','Ex','2006-02-13','lm'),
	('Holon Phantoms','Ex','2006-05-03','hp'),
	('Crystal Guardians','Ex','2006-08-30','cg'),
	('Dragon Frontiers','Ex','2006-11-08','df'),
	('Power Keepers','Ex','2007-02-14','pk'),
	('Diamond & Pearl','Diamond & Pearl','2007-05-23','dp'),
	('Mysterious Treasures','Diamond & Pearl','2007-08-22','mt'),
	('Secret Wonders','Diamond & Pearl','2007-11-07','sw'),
	('Great Encounters','Diamond & Pearl','2008-02-13','ge'),
	('Majestic Dawn','Diamond & Pearl','2008-05-21','md'),
	('Legends Awakened','Diamond & Pearl','2008-08-20','la'),
	('Stormfront','Diamond & Pearl','2008-11-05','sf'),
	('Platinum','Platinum','2009-02-11','pl'),
	('Rising Rivals','Platinum','2009-05-16','rr'),
	('Supreme Victors','Platinum','2009-08-19','sv'),
	('Arceus','Platinum','2009-11-04','ar'),
	('HeartGold & SoulSilver','HeartGold & SoulSilver','2010-02-10','hs'),
	('Unleashed','HeartGold & SoulSilver','2010-05-12','ul'),
	('Undaunted','HeartGold & SoulSilver','2010-08-18','ud'),
	('Triumphant','HeartGold & SoulSilver','2010-11-03','tm'),
	('Call of Legends','Call of Legends','2011-02-09','cl'),
	('Black & White','Black & White','2011-04-25','blw'),
	('Emerging Powers','Black & White','2011-08-31','epo'),
	('Noble Victories','Black & White','2011-11-16','nvi'),
	('Next Destinies','Black & White','2012-02-08','nxd'),
	('Dark Explorers','Black & White','2012-05-09','dex'),
	('Dragons Exalted','Black & White','2012-08-15','drx'),
	('Dragon Vault','Black & White','2012-10-05','drv'),
	('Boundaries Crossed','Black & White','2012-11-07','bcr'),
	('Plasma Storm','Black & White','2013-02-06','pls'),
	('Plasma Freeze','Black & White','2013-05-08','plf'),
	('Plasma Blast','Black & White','2013-08-14','plb'),
	('Legendary Treasures','Black & White','2013-11-06','ltr'),
	('Kalos Starter Set','XY','2013-11-08','kss'),
	('XY','XY','2014-02-5','xy'),
	('Flashfire','XY','2014-05-07','flf'),
	('Forious Fists','XY','2014-08-13','ffi'),
	('Phantom Forces','XY','2014-11-05','phf'),
	('Primal Clash','XY','2015-02-04','prc'),
	('Double Crisis','XY','2015-03-25','dcr'),
	('Roaring Skies','XY','2015-05-6','ros'),
	('Ancient Origins','XY','2015-08-12','aor'),
	('BREAKthrough','XY','2015-11-04','bkt'),
	('BREAKpoint','XY','2016-02-03','bkp'),
	('Generations','XY','2016-02-22','gen'),
	('Fates Collide','XY','2016-05-02','fco'),
	('Steam Siege','XY','2016-08-03','sts'),
	('Evolutions','XY','2016-11-02','evo'),
	('Sun & Moon','Sun & Moon','2017-02-03','sum'),
	('Guardians Rising','Sun & Moon','2017-05-05','gri'),
	('Burning Shadows','Sun & Moon','2017-08-04','bus'),
	('Shinning Legends','Sun & Moon','2017-10-06','slg'),
	('Crimson Invasion','Sun & Moon','2017-11-03','cin'),
	('Ultra Prism','Sun & Moon','2018-02-02','upr'),
	('Forbidden Light','Sun & Moon','2018-05-04','fli'),
	('Celestial Storm','Sun & Moon','2018-08-03','ces'),
	('Dragon Majesty','Sun & Moon','2018-09-07','drm'),
	('Lost Thunder','Sun & Moon','2018-11-02','lot'),
	('Team Up','Sun & Moon','2019-02-01','teu'),
	('Detective Pikachu','Sun & Moon','2019-04-29','det'),
	('Unbroken Bonds','Sun & Moon','2019-05-03','unb'),
	('Unified Minds','Sun & Moon','2019-08-02','unm'),
	('Hidden Fates','Sun & Moon','2019-08-23','hif'),
	('Cosmic Eclipse','Sun & Moon','2019-11-01','cec'),
	('Sword & Shield','Sword & Shield','2020-02-07','ssh'),
	('Rebel Clash','Sword & Shield','2020-05-01','rcl'),
	('Darkness Ablaze','Sword & Shield','2020-08-14','daa'),
	('Champion''s Path','Sword & Shield','2020-09-25','cpa'),
	('Vivid Voltage','Sword & Shield','2020-11-13','viv'),
	('Shinning Fates','Sword & Shield','2021-02-19','shf'),
	('Battle Styles','Sword & Shield','2021-04-19','bst'),
	('Chilling Reign','Sword & Shield','2021-06-18','cre'),
	('Evolving Skies','Sword & Shield','2021-08-27','evs'),
	('Celebrations','Sword & Shield','2021-10-08','cel'),
	('Fusion Strike','Sword & Shield','2021-11-12','fst'),
	('Brilliant Stars','Sword & Shield','2022-02-25','brs'),
	('Astral Radiance','Sword & Shield','2022-05-27','asr'),
	('Pokemon Go','Sword & Shield','2022-07-01','pgo'),
	('Lost Origin','Sword & Shield','2022-09-09','lor'),
	('Silver Tempest','Sword & Shield','2022-11-11','sit'),
	('Crown Zenith','Sword & Shield','2023-01-20','crz'),
	('Scarlet & Violet','Scarlet & Violet','2023-03-31','svi'),
	('Paldea Evolved','Scarlet & Violet','2023-07-09','pal'),
	('Obsidian Flames','Scarlet & Violet','2023-08-11','obf'),
	('151','Scarlet & Violet','2023-09-22','mew'),
	('Paradox Rift','Scarlet & Violet','2023-11-03','par'),
	('Paldean Fates','Scarlet & Violet','2024-01-26','paf'),
	('Temporal Forces','Scarlet & Violet','2024-02-22','tef'),
	('Twilight Masquerade','Scarlet & Violet','2024-05-24','twm'),
	('Shrouded Fable','Scarlet & Violet','2024-08-02','sfa'),
	('Stellar Crown','Scarlet & Violet','2024-09-13','scr'),
	('Surging Spark','Scarlet & Violet','2024-11-08','srp'),
	('Prismatic Evolutions','Scarlet & Violet','2025-01-17','pre'),
	('Journey Together','Scarlet & Violet','2025-03-28','jtg'),
	('Destined Rivals','Scarlet & Violet','2025-05-30','dri'),
	('Black Bolt','Scarlet & Violet','2025-07-18','blk'),
	('White Flare','Scarlet & Violet','2025-07-18','wht'),
	('Mega Evolution','Mega Evolution','2025-09-26','meg'),
	('Phantasmal Flames','Mega Evolution','2025-11-14','pfl'),
	('Wizards Promo','Black Star','1999-07-01','wp'),
	('Nintendo Promo','Black Star','2003-10-01','np'),
	('Diamond & Pearl Promo','Black Star','2007-05-01','dpp'),
	('HeartGold & SoulSilver Promo','Black Star','2010-02-01','hsp'),
	('Black & White Promo','Black Star','2011-04-01','bwp'),
	('XY Promo','Black Star','2013-10-01','xyp'),
	('Sun & Moon Promo','Black Star','2016-11-01','smp'),
	('Sword & Shield Promo','Black Star','2019-11-01','ssp'),
	('Scarlet & Violet Promo','Black Star','2023-01-01','svp'),
	('Mega Evolution Promo','Black Star','2025-09-01','mep'),
	('McDonald''s 2011','McDonald''s Collection','2011-06-17','m11'),
	('McDonald''s 2012','McDonald''s Collection','2012-06-15','m12'),
	('McDonald''s 2013','McDonald''s Collection','2013-10-13','m13'),
	('McDonald''s 2014','McDonald''s Collection','2014-05-23','m14'),
	('McDonald''s 2015','McDonald''s Collection','2015-10-14','m15'),
	('McDonald''s 2016','McDonald''s Collection','2016-08-19','m16'),
	('McDonald''s 2017','McDonald''s Collection','2017-07-01','m17'),
	('McDonald''s 2018','McDonald''s Collection','2018-10-16','m18'),
	('McDonald''s 2019','McDonald''s Collection','2019-10-15','m19'),
	('McDonald''s 2021','McDonald''s Collection','2021-02-09','m21'),
	('McDonald''s 2022','McDonald''s Collection','2022-08-03','m22'),
	('McDonald''s 2023','McDonald''s Collection','2023-07-27','m23'),
	('McDonald''s 2024','McDonald''s Collection','2024-10-04','m24'),
	('Trick or Trade 2022','Trick or Trade','2022-09-01','tt22'),
	('Trick or Trade 2023','Trick or Trade','2023-09-01','tt23'),
	('Trick or Trade 2024','Trick or Trade','2024-08-30','tt24'),
	('POP 1','POP','2004-09-01','pop1'),
	('POP 2','POP','2005-08-01','pop2'),
	('POP 3','POP','2006-04-01','pop3'),
	('POP 4','POP','2006-08-01','pop4'),
	('POP 5','POP','2007-04-01','pop5'),
	('POP 6','POP','2007-09-01','pop6'),
	('POP 7','POP','2008-04-01','pop7'),
	('POP 8','POP','2008-09-01','pop8'),
	('POP 9','POP','2009-03-01','pop9'),
	('Play! 1','Play! Pokemon Prize Pack','2022-11-09','pps1'),
	('Play! 2','Play! Pokemon Prize Pack','2023-01-19','pps2'),
	('Play! 3','Play! Pokemon Prize Pack','2023-08-14','pps3'),
	('Play! 4','Play! Pokemon Prize Pack','2024-02-14','pps4'),
	('Play! 5','Play! Pokemon Prize Pack','2024-08-14','pps5'),
	('Play! 6','Play! Pokemon Prize Pack','2025-02-14','pps6'),
	('Play! 7','Play! Pokemon Prize Pack','2025-08-14','pps7'),
	('Southern Island','Miscellaneous','2001-07-31','sl'),
	('Best of Game','Miscellaneous','2002-12-01','best'),
	('Poke Card Creator Pack','Miscellaneous','2004-07-01','cc'),
	('Pokemon Rumble','Miscellaneous','2009-12-02','rm'),
	('Pokemon Futsal','Miscellaneous','2020-09-11','fut20')
GO

PRINT '*** adding to Card Table ***'
GO
INSERT INTO [dbo].[PokemonCard]
	(
		[ArtistID],[AbilityID],[BoosterID],[PokemonRuleID],[ElementTypeID],
		[Name],[BoosterNumber],[CardType],[Rarity],[WeaknessType],
		[ResistanceType],[WeaknessValue],[ResistanceValue],[RetreatCost],
		[Health],[Stage]
	)
VALUES
	(12,'power saver','Destined Rivals','Pokemon-EX','fire','Team Rocket''s Mewtwo EX',213,'pokemon','Special Illustration Rare','dark','fighting',2,30,3,280,'basic'),
	(14,'none','Destined Rivals','Pokemon-EX','colorless','Thi''s Card is a Test.',999,'pokemon','Special Illustration Rare','dark','fighting',2,30,3,280,'basic')
GO

PRINT '*** adding to Card Move Table ***'
GO
INSERT INTO [dbo].[CardMove]
	([PokemonCardID],[MoveID])
VALUES
	(1,'erasure ball'),
	(1,'test')
GO

PRINT '*** adding to Card Alternate Art Table ***'
GO
INSERT INTO [dbo].[CardAlternateArt]
	([PokemonCardID],[AlternateArtID])
VALUES
	(1,'jumbo'),
	(1,'reverse holo'),
	(2,'none'),
	(2,'jumbo')
GO