PRINT '' PRINT '*** using tcg_db'
GO
USE [tcg_db]
GO

PRINT '' PRINT '' PRINT 'Adding values to Tables in tcg_db'

PRINT '*** adding to Role Table ***'
GO
INSERT INTO [dbo].[Role]
	([RoleID],[Description])
VALUES
	('Admin','This user can create an entry for new cards, boosters,
		artist, alternate arts, abilitys, element types, moves, pokedex, pokemon rules,
		stages, stage evolutions, or pokemon evolutions'),
	
	('General','This is the standard user can not create new cards, boosters,
		artist, alternate arts, abilitys, element types, moves, pokedex, pokemon rules,
		stages, stage evolutions, or pokemon evolutions')
GO

PRINT '*** adding to Users Table ***'
GO
INSERT INTO [dbo].[Users]
	([GivenName],[Surname],[Email])
VALUES
	('john','stewart','john@mail.com'),
	('ceedee','lamb','lamb@mail.com'),
	('daniel','jones','daniel@mail.com'),
	('harrison','mevis','mevis@mail.com'),
	('tom','ford','tom@mail.com')
GO

PRINT '*** adding to UserRole Table ***'
GO
INSERT INTO [dbo].[UserRole]
	([RoleID],[UserID])
VALUES
	('Admin',10000),
	('General',10001),
	('General',10002),
	('General',10003),
	('General',10004)
GO

PRINT '*** adding to AlternateArt Table ***'
GO
INSERT INTO [dbo].[AlternateArt]
	([AlternateArtID],[Description])
VALUES
	('none','standard card'),
	('promo','card given in boxes or bundles rathern than a pack'),
	('reverse holo','same as a standard card but the background has foil rather than the picture'),
	('reverse holo pokeball','same as reverse holo but has pokeballs on the foil'),
	('reverse holo master ball','same as reverse holo but has master balls on the foil')
GO

PRINT '*** adding to Ability Table ***'
GO
INSERT INTO [dbo].[Ability]
	([AbilityID],[AbilityType],[Description])
VALUES

('rain dance','pokémon power','As often as you like during your turn (before your attack), you may attach 1 Water Energy card to 1 of your Water Pokémon. (This doesn''t use up your 1 Energy card attachment for the turn.) This power can''t be used if Blastoise is Asleep, Confused, or Paralyzed.'),
('strikes back','pokémon power','Whenever your opponent''s attack damages Machamp (even if Machamp is Knocked Out), this power does 10 damage to the attacking Pokémon. (Don''t apply Weakness and Resistance.) This power can''t be used if Machamp is Asleep, Confused, or Paralyzed when your opponent attacks.'),
('energy trans','pokémon power','As often as you like during your turn (before your attack), you may take 1 Grass Energy card attached to 1 of your Pokémon and attach it to a different one. This power can''t be used if your pokemon is Asleep, Confused, or Paralyzed.'),
('invisible wall','pokémon power','Whenever an attack (including your own) does 30 or more damage to Mr. Mime (after applying Weakness and Resistance), prevent that damage. (Any other effects of attacks still happen.) This power can''t be used if Mr. Mime is Asleep, Confused, or Paralyzed.'),
('thick skinned','pokémon power','Snorlax can''t become Asleep, Confused, Paralyzed, or Poisoned. This power can''t be used if Snorlax is already Asleep, Confused, or Paralyzed.'),
('shift','pokémon power','Once during your turn (before your attack), you may change the type of Venomoth to the type of any other Pokémon in play other than Colorless. This power can''t be used if Venomoth is Asleep, Confused, or Paralyzed.')
GO

PRINT '*** adding to ElementType Table ***'
GO
INSERT INTO [dbo].[ElementType]
	([ElementTypeID],[Description])
VALUES
	('colorless',''),
	('fire',''),
	('water',''),
	('grass',''),
	('electric',''),
	('ice',''),
	('fighting',''),
	('poison',''),
	('ground',''),
	('flying',''),
	('psychic',''),
	('bug',''),
	('rock',''),
	('ghost',''),
	('dragon',''),
	('dark',''),
	('steel',''),
	('fairy','')
GO

PRINT '*** adding to Move Table ***'
GO
INSERT INTO [dbo].[Move]
	([MoveID],[Damage],[Description])
VALUES
	('shadow bind',150,'During your opponent''s next turn, the Defending Pokemon can''t retreat.'),
	('merciless blade',110,'If your opponent''s active pokemon already has any damage counters on it, this attack does 100 damage.')
GO

PRINT '*** adding to MoveCost ***'
GO
INSERT INTO [dbo].[MoveCost]
	([MoveID],[ElementTypeID],[Quantity])
VALUES
	('shadow bind','psychic',2),
	('shadow bind','colorless',1),
	('merciless blade','dark',2)
GO

PRINT '*** adding to Artist Table ***'
GO
INSERT INTO [dbo].[Artist]
	([GivenName],[Surname])
VALUES
	('a-g',''),
	('5ban','graphics'),
	('0313',''),
	('2003 pikachu','project'),
	('2004 pikachu','project'),
	('2005 pikachu','project'),
	('2006 pikachu','project'),
	('2009 pikachu','project'),
	('2014 pikachu','project'),
	('2017 pikachu','project'),
	('2018 pikachu','project'),
	('2019 pikachu','project'),
	('2020 pikachu','project'),
	('ack cg','works'),
	('acorviart',''),
	('adidas enjin','project'),
	('ai','kurihara'),
	('aimi','tomita'),
	('akagi',''),
	('akino','fukuji'),
	('akira','egawa'),
	('akira','komayama'),
	('aky cg','works'),
	('aliya','chen'),
	('amelicart',''),
	('anderson',''),
	('anesaki','dynamic'),
	('aoki',''),
	('apios',''),
	('arai','kiriko'),
	('asako','ito'),
	('aspara',''),
	('asuka','iwashita'),
	('atsuko','nishida'),
	('atsuko','ujiie'),
	('atsushi','furusawa'),
	('atsuya','uki'),
	('avec','yoko'),
	('ayaka','yoshida'),
	('ayako','ozaki'),
	('aya','kusube'),
	('ayoka','yoshida'),
	('ayumi','odashima'),
	('benimaru','itoh'),
	('beruburi',''),
	('big mama','tagawa'),
	('booota',''),
	('buchi',''),
	('bun','toujo'),
	('burari',''),
	('chibi',''),
	('christopher','rush'),
	('cochi8i',''),
	('cona','nitanda'),
	('conceptlab',''),
	('craig','turvey'),
	('cr cg','gangs'),
	('d.a.g','inc.'),
	('daisuke','ito'),
	('daisuke','iwamoto'),
	('daisuke','ochiai'),
	('danciao',''),
	('demizuposuka',''),
	('dom',''),
	('dr.ooyama',''),
	('dsuke',''),
	('ebila',''),
	('emi','ando'),
	('emi','miwa'),
	('emi','yoshida'),
	('en','morikura'),
	('eri','kamei'),
	('eri','yamaki'),
	('eske','yoshinob'),
	('etsuya','hattori'),
	('felicia','chen'),
	('framestore',''),
	('fujimoto','gold'),
	('fumie','kittaka'),
	('fuzichoco',''),
	('gakuji','nomoto'),
	('game freak','inc.'),
	('gapao',''),
	('gemi',''),
	('gidora',''),
	('ginga',''),
	('gogotake',''),
	('gosho','aoyama'),
	('gossan',''),
	('goto','minori'),
	('hagiya','kaoru'),
	('hajime','kusajima'),
	('hanabushi',''),
	('hanako',''),
	('haru','akasaka'),
	('haruko','ichikawa'),
	('hasegawa','saki'),
	('hasuno',''),
	('hatachu',''),
	('hataya',''),
	('heisuke','kitazawa'),
	('hico','kim'),
	('hideaki','hakozaki'),
	('hideki','ishikawa'),
	('hideki','kazama'),
	('hideyuki','nakajima'),
	('hiiroki','asanuma'),
	('hikaru','koike'),
	('hiranobu','uoshida'),
	('hiroaki','ito'),
	('hiroki','asanuma'),
	('hiroki','fuchino'),
	('hiromichi','sugiyama'),
	('hiron',''),
	('hironobu','yoshida'),
	('hirotaka','marufuji'),
	('hiroyuki','yamamoto'),
	('hisao','nakamura'),
	('hitoshi','ariga'),
	('hizuki','misono'),
	('hncl',''),
	('hoshino','kuro'),
	('huang tzu','en'),
	('hyogonosuke',''),
	('ikeda','saki'),
	('imakuni',''),
	('imakunki',''),
	('imoniii',''),
	('inose','yukie'),
	('iori','suzuki'),
	('ito','kyoko'),
	('ito','kyoto'),
	('iwaiya',''),
	('iwamoto05',''),
	('izucch',''),
	('james','turner'),
	('jerky',''),
	('jiro','sasumo'),
	('jiro','sasuno'),
	('julie','hang'),
	('jumpei','akasaka'),
	('jungo','suzuki'),
	('junsei','kuninobu'),
	('k.','hoshiba'),
	('k.','utsunomiya'),
	('kadama',''),
	('kagemaru','himeno'),
	('kai','ishikawa'),
	('kamome','shirahama'),
	('kamonabe',''),
	('kanahei',''),
	('kanako','eo'),
	('kanami','ogata'),
	('kantaro',''),
	('kariya',''),
	('kasumi','matsuda'),
	('katsunori','sato'),
	('katsura','tabata'),
	('kawayoo',''),
	('kazuaki','aihara'),
	('kazuhiko','nishihara'),
	('kazuki','minami'),
	('kazuma','koda'),
	('kazumasa','yasukuni'),
	('kazuo','yazawa'),
	('kazuyuki','kano'),
	('kedamahadaitai','yawarakai'),
	('kei','hoshinba'),
	('keiichiro','ito'),
	('keiji','kinebuchi'),
	('keiko','fukuyama'),
	('keiko','moritsugu'),
	('keisin',''),
	('keita','komatsuya'),
	('keita','takahashi'),
	('ken','ikuji'),
	('kenkichi','toyama'),
	('ken','sugimori'),
	('kent','kanetsuna'),
	('kg-2000',''),
	('k','hoshiba'),
	('kimiya','masago'),
	('kinu','nishimura'),
	('kirisaki',''),
	('kiyotaka','oshiyama'),
	('kodama',''),
	('koji','nakata'),
	('kouji','tajima'),
	('kouki','saitou'),
	('krgc',''),
	('kunihiko','yuyama'),
	('kurata','so'),
	('kuroimori',''),
	('kurumitsu',''),
	('kyoko','koizumi'),
	('kyoko','umemoto'),
	('kyupiyama',''),
	('lee','hyunjung'),
	('lee','mina'),
	('ligton',''),
	('linne',''),
	('m.','akiyama'),
	('mahou',''),
	('maiko','fujiwara'),
	('makato','mizobuchi'),
	('makoto','imai'),
	('makoto','mizobuchi'),
	('makura','tami'),
	('mame','akimaru'),
	('mana','ibe'),
	('marina','chikazawa'),
	('masa',''),
	('masahiko','ishii'),
	('masakazu','fukuda'),
	('masako','tomii'),
	('masako','yamashita'),
	('mashu',''),
	('maskazu','fukuda'),
	('matazo',''),
	('match',''),
	('matofumi','fujiwara'),
	('mazakaza','fukuda'),
	('megumi','higuchi'),
	('megumi','mizutani'),
	('mekayu',''),
	('mele',''),
	('midori','harada'),
	('miho','asada'),
	('mika','pikazo'),
	('mikiko','takeda'),
	('miki','kudo'),
	('mikio','menjo'),
	('miki','tanak'),
	('miki','tanaka'),
	('milky','isobe'),
	('minahamu',''),
	('minaminami','take'),
	('mina','nakai'),
	('minato',''),
	('mingo',''),
	('mio','muroi'),
	('miranda','branley'),
	('misaki','hashimoto'),
	('misaki','hasimoto'),
	('misa','tsutsui'),
	('mitsuhiro','arita'),
	('mizue',''),
	('mori','yuu'),
	('motofumi','fujiwara'),
	('mousho',''),
	('mpc','film'),
	('mt.','tbt'),
	('mugenup',''),
	('mugi','hamada'),
	('n-design','inc.'),
	('nabana','kensaku'),
	('nabatame','kazutaka'),
	('nagano',''),
	('nagimiso',''),
	('nagomi','nijo'),
	('nakamura','ippan'),
	('nakano','satoshi'),
	('nakaoka',''),
	('naoki','saito'),
	('naoyo','kimura'),
	('narano',''),
	('narumi','sato'),
	('natsuko shinji','ete'),
	('natsumi','miyanose'),
	('natsumi','yoshida'),
	('natsumi','yoshisda'),
	('nc','empire'),
	('n design','inc.'),
	('nelnal',''),
	('nisimono',''),
	('nisota','niso'),
	('noboyuki','hobu'),
	('nobuhiro','imagawa'),
	('nobuyuki','fujimoto'),
	('nobuyuki','habu'),
	('noriko','hotta'),
	('noriko','takaya'),
	('noriko','uono'),
	('nousawa','mochipuyo'),
	('nurikabe',''),
	('okacheke',''),
	('okayamatakatoshi',''),
	('oku',''),
	('okubo',''),
	('ooyama',''),
	('orbitallink','inc.'),
	('orca',''),
	('osare',''),
	('oswaldo','kato'),
	('otumami',''),
	('ounishi',''),
	('pani','kobayashi'),
	('pikamania',''),
	('planeta',''),
	('planeta','hiiragi'),
	('planeta','igarashi'),
	('planeta','mochizuiki'),
	('planeta','mochizuki'),
	('planeta','otani'),
	('planeta','tsuji'),
	('planeta','yamashita'),
	('po-suzuki',''),
	('pokemon get','tv'),
	('pokemon','rumble'),
	('q-rais',''),
	('raita','kazama'),
	('reiko','tanoue'),
	('rend',''),
	('reospikee',''),
	('rianti','hidayat'),
	('rika',''),
	('rina',''),
	('rond',''),
	('ryoma','uratsuka'),
	('ryota','muramasa'),
	('ryota','murayama'),
	('ryota','saito'),
	('ryo','ueda'),
	('ryuta','fuse'),
	('ryuta','kusumi'),
	('saboteri',''),
	('sachiko','adachi'),
	('sachiko','eba'),
	('sachi','matoba'),
	('sadaji',''),
	('saino','misaki'),
	('saki','hayashiro'),
	('sakiko','maeda'),
	('saki','yahashiro'),
	('sanosuke','sakuma'),
	('satoma',''),
	('satoshi','nakai'),
	('satoshi','ohta'),
	('satoshi','shirai'),
	('satoshi','yamamoto'),
	('sayaka','maruyama'),
	('saya','tsuruta'),
	('sayuri','ichiishi'),
	('scav',''),
	('sekio',''),
	('shiburingaru',''),
	('shibuzoh.',''),
	('shigenori','negishi'),
	('shimaris','yukichi'),
	('shimeris','yukichi'),
	('shin-ichi','yoshida'),
	('shin-ichi','yoshikawa'),
	('shinji','higuchi'),
	('shinji','kanda'),
	('shin','nagasawa'),
	('shinya','komatsu'),
	('shinya','mazuno'),
	('shinya','mizuno'),
	('shizurow',''),
	('shoko','nakagawa'),
	('sie','nanahara'),
	('siwama','chiaki'),
	('so-taro',''),
	('souchirou','gunjima'),
	('souichirou','gunjima'),
	('sowsow',''),
	('spike','chunsoft.'),
	('studio bora','inc'),
	('studio bora','inc.'),
	('sui',''),
	('sumiyoshi','kitzuki'),
	('sumiyoshi','kizuki'),
	('susumu','maeya'),
	('suwama','chiaki'),
	('svlt',''),
	('t.','honda'),
	('taiga','kasai'),
	('taiga','kayama'),
	('taira','akitsu'),
	('takabon',''),
	('takahiro','yamashita'),
	('takao','unno'),
	('takashi','shiraishi'),
	('takashi','yamaguchi'),
	('take',''),
	('takeshia','nakamura'),
	('takeshi','nakamura'),
	('takumi','akabane'),
	('takumi','wada'),
	('takuyoa',''),
	('teeziro',''),
	('tekashi','shiraishi'),
	('terada','tera'),
	('tetsu','kayama'),
	('tetsuo','hara'),
	('tetsuo','yajima'),
	('tetsuya','koizumi'),
	('pokemon company','art team'),
	('tika','matsuno'),
	('tika','matusno'),
	('toi8',''),
	('tokichan',''),
	('tokiya',''),
	('tokumi','akabane'),
	('tomiyasu','daiki'),
	('tomoaki','imakuni'),
	('tomohiro','kitakaze'),
	('tomokazu','komiya'),
	('tomoko','wakai'),
	('tomomi','kaneko'),
	('tomomi','ozaki'),
	('tomomo','ozaki'),
	('tomowaka',''),
	('tonji','matsuno'),
	('tono',''),
	('toriyufu',''),
	('toshinao','aoki'),
	('toyste',''),
	('toyste','beach'),
	('tsuyoshi','nagano'),
	('uninori',''),
	('usgmen',''),
	('uta',''),
	('wataru','kawahara'),
	('whisker',''),
	('wintr','wandr'),
	('y.','fujishima'),
	('yamazaki','rei'),
	('yano','keiji'),
	('yashiro','nanaco'),
	('yasuda','shuhei'),
	('yasuki','watanabe'),
	('yoichi','katabe'),
	('yoko','hishida'),
	('yoriuki','ikegami'),
	('yoriyuki','ikegami'),
	('yoshimi','miyoshi'),
	('yoshinobu','saito'),
	('yoshioka',''),
	('yosuke da','silva'),
	('you','iribi'),
	('yousuke','hirata'),
	('yuichi','sawayama'),
	('yuka','morii'),
	('yuka','tanaka'),
	('yukihiro','tada'),
	('yukiko','baba'),
	('yumi',''),
	('yu','nagaba'),
	('yuriko','akase'),
	('yuri','umemura'),
	('yusuke','ishikawa'),
	('yusuke','kozaki'),
	('yusuke','ohmura'),
	('yusuke','shimada'),
	('yuu',''),
	('yuuki','kawamura'),
	('yuu','nishida'),
	('yuya','oka'),
	('zig',''),
	('zu-ka','')
GO
/*
	add unique for pokemon name, ElementType, boosterName/Abbreviation GenerationName



PRINT '*** adding to Booster Table ***'
GO
INSERT INTO [dbo].[Booster]
	([GenerationName],[GenerationNumber],[BoosterName],[BoosterNumber],
	[BoosterType],[ReleaseDate],[Abbreviation]) 
VALUES
	('original series',1,'base set',1,'main series expansion','1999-01-09','bs'),
	('original series',1,'jungle',2,'main series expansion','1999-06-16','ju'),
	('original series',1,'fossil',3,'main series expansion','1999-10-10','fo'),
	('original series',1,'base set 2',4,'main series expansion','2000-02-24','b2'),
	('original series',1,'team rocket',5,'main series expansion','2000-04-24','tr'),
	('original series',1,'gym heroes',6,'main series expansion','2000-08-14','g1'),
	('original series',1,'gym challenge',7,'main series expansion','2000-10-16','g2'),
	('neo series',2,'neo genesis',8,'main series expansion','2000-12-16','n1'),
	('neo series',2,'neo discovery',9,'main series expansion','2001-06-01','n2'),
	('neo series',2,'neo revelation',10,'main series expansion','2001-09-21','n3'),
	('neo series',2,'neo destiny',11,'main series expansion','2002-02-28','n4'),
	('legendary collection series',3,'legendary collection',12,'main series expansion','2002-05-24','lc'),
	('e Card Series',4,'expedition base set',13,'main series expansion','2002-09-15','ex'),
	('e Card Series',4,'aquapolis',14,'main series expansion','2003-01-15','aq'),         
	('e Card Series',4,'skyridge',15,'main series expansion','2003-05-12','sk'),           
	('ex series',5,'ruby and sapphire',16,'main series expansion','2003-07-18','rs'),    
	('ex series',5,'sandstorm',17,'main series expansion','2003-09-18','ss'),            
	('ex series',5,'dragon',18,'main series expansion','2003-11-24','dr'),                 
	('ex series',5,'team magma vs team aqua',19,'main series expansion','2004-03-15','ma'),
	('ex series',5,'hidden legends',20,'main series expansion','2004-06-14','hl'),         
	('ex series',5,'fire red & leaf green',21,'main series expansion','2004-08-30','rg'),  
	('ex series',5,'team rocket returns',22,'main series expansion','2004-11-08','trr'),   
	('ex series',5,'deoxys',23,'main series expansion','2005-02-14','dx'),                 
	('ex series',5,'emerald',24,'main series expansion','2005-05-09','em'),                
	('ex series',5,'unseen forces',25,'main series expansion','2005-08-22','uf'),          
	('ex series',5,'delta species',26,'main series expansion','2005-10-31','ds'),          
	('ex series',5,'legend maker',27,'main series expansion','2006-02-13','lm'),           
	('ex series',5,'holon phantoms',28,'main series expansion','2006-05-03','hp'),         
	('ex series',5,'crystal guardians',29,'main series expansion','2006-08-30','cg'),  
	('ex series',5,'dragon frontiers',30,'main series expansion','2006-11-08','df'),       
	('ex series',5,'power keepers',31,'main series expansion','2007-02-14','pk'),          
	('diamond & pearl series',6,'diamond & pearl',32,'main series expansion','2007-05-23','dp'),          
	('diamond & pearl series',6,'mysterious treasures',33,'main series expansion','2007-08-22','mt'),          
	('diamond & pearl series',6,'secret wonders',34,'main series expansion','2007-11-07','sw'),          
	('diamond & pearl series',6,'great encounters',35,'main series expansion','2008-02-13','ge'),          
	('diamond & pearl series',6,'majestic dawn',36,'main series expansion','2008-05-21','md'),          
	('diamond & pearl series',6,'legends awakened',37,'main series expansion','2008-08-20','la'),          
	('diamond & pearl series',6,'stormfront',38,'main series expansion','2008-11-05','sf'),      
	('platinum series',7,'platinum',39,'main series expansion','2009-02-11','pl'),      
	('platinum series',7,'rising rivals',40,'main series expansion','2009-05-16','rr'),      
	('platinum series',7,'supreme victors',41,'main series expansion','2009-08-19','sv'),      
	('platinum series',7,'arceus',42,'main series expansion','2009-11-04','ar'),   
	('heart gold & soul silver series',8,'heart gold & soul silver',43,'main series expansion','2010-02-10','hs'),   
	('heart gold & soul silver series',8,'unleashed',44,'main series expansion','2010-05-12','ul'),   
	('heart gold & soul silver series',8,'undaunted',45,'main series expansion','2010-08-18','ud'),   
	('heart gold & soul silver series',8,'triumphant',46,'main series expansion','2010-11-03','tm'),   
	('heart gold & soul silver series',8,'call of legends',47,'main series expansion','2011-02-09','cl'),  
	('black & white series',9,'black & white',48,'main series expansion','2011-04-25','blw'),  
	('black & white series',9,'emerging powers',49,'main series expansion','2011-08-31','epo'),  
	('black & white series',9,'noble victories',50,'main series expansion','2011-11-16','nvi'),  
	('black & white series',9,'next destinies',51,'main series expansion','2012-02-08','nxd'),  
	('black & white series',9,'dark explorers',52,'main series expansion','2012-05-09','dex'),  
	('black & white series',9,'dragons exalted',53,'main series expansion','2012-08-15','drx'),  
	('black & white series',9,'dragon vault',54,'special expansion','2012-10-05','drv'),  
	('black & white series',9,'boundaries crossed',55,'main series expansion','2012-11-07','bcr'),  
	('black & white series',9,'plasma storm',56,'main series expansion','2013-02-06','pls'),  
	('black & white series',9,'plasma freeze',57,'main series expansion','2013-05-08','plf'),  
	('black & white series',9,'plasma blast',58,'main series expansion','2013-08-14','plb'),  
	('black & white series',9,'legendary treasures',59,'main series expansion','2013-11-06','ltr')  
	
GO

*/