PRINT '' PRINT '*** using tcg_db'
GO
USE [tcg_db]
GO

PRINT '' PRINT '' PRINT 'Adding values to Tables in tcg_db'

PRINT '*** adding to Role Table ***'
GO
INSERT INTO [dbo].[Role]
	([RoleID],[Description])
VALUES
	('Admin','This user can create an entry for new cards, boosters,
		artist, alternate arts, abilitys, element types, moves, pokedex, pokemon rules,
		stages, stage evolutions, or pokemon evolutions'),
	
	('General','This is the standard user can not create new cards, boosters,
		artist, alternate arts, abilitys, element types, moves, pokedex, pokemon rules,
		stages, stage evolutions, or pokemon evolutions'),
		
	('Moderator','This user can manage most aspects of the website. But can''t manage the active status of series or boosters. Also can''t manage permanent deletions.')
GO

PRINT '*** adding to Users Table ***'
GO
INSERT INTO [dbo].[Users]
	([GivenName],[Surname],[Email])
VALUES
	('john','stewart','john@mail.com'),
	('ceedee','lamb','lamb@mail.com'),
	('daniel','jones','daniel@mail.com'),
	('harrison','mevis','mevis@mail.com'),
	('tom','ford','tom@mail.com')
GO

PRINT '*** adding to UserRole Table ***'
GO
INSERT INTO [dbo].[UserRole]
	([RoleID],[UserID])
VALUES
	('Admin',10000),
	('General',10001),
	('Moderator',10001),
	('General',10002),
	('General',10003),
	('General',10004)
GO

PRINT '*** adding to AlternateArt Table ***'
GO
INSERT INTO [dbo].[AlternateArt]
	([AlternateArtID],[Description])
VALUES
	('none','standard card'),
	('promo','varies between card.'),
	('pokemon center','stamp on the right side that has a pokemon center logo.'),
	('jumbo','oversized cards that come in special boxes.'),
	('reverse holo','same as a standard card but the background has foil rather than the picture.'),
	('reverse holo pokeball','same as reverse holo but has pokeballs on the foil.'),
	('reverse holo master ball','same as reverse holo but has master balls on the foil.')
GO

PRINT '*** adding to Ability Table ***'
GO
INSERT INTO [dbo].[Ability]
	([AbilityID],[AbilityType],[Description])
VALUES
	('none','none','none'),
	('Rain Dance','pokemon power','As often as you like during your turn (before your attack), you may attach 1 Water Energy card to 1 of your Water Pokémon. (This doesn''t use up your 1 Energy card attachment for the turn.) This power can''t be used if Blastoise is Asleep, Confused, or Paralyzed.'),
	('Strikes Back','pokemon power','Whenever your opponent''s attack damages Machamp (even if Machamp is Knocked Out), this power does 10 damage to the attacking Pokémon. (Don''t apply Weakness and Resistance.) This power can''t be used if Machamp is Asleep, Confused, or Paralyzed when your opponent attacks.'),
	('Energy Trans','pokemon power','As often as you like during your turn (before your attack), you may take 1 Grass Energy card attached to 1 of your Pokémon and attach it to a different one. This power can''t be used if your pokemon is Asleep, Confused, or Paralyzed.'),
	('Invisible Wall','pokemon power','Whenever an attack (including your own) does 30 or more damage to Mr. Mime (after applying Weakness and Resistance), prevent that damage. (Any other effects of attacks still happen.) This power can''t be used if Mr. Mime is Asleep, Confused, or Paralyzed.'),
	('Thick Skinned','pokemon power','Snorlax can''t become Asleep, Confused, Paralyzed, or Poisoned. This power can''t be used if Snorlax is already Asleep, Confused, or Paralyzed.'),
	('Shift','pokemon power','Once during your turn (before your attack), you may change the type of Venomoth to the type of any other Pokémon in play other than Colorless. This power can''t be used if Venomoth is Asleep, Confused, or Paralyzed.'),
	('Power Saver','ability','This Pokemon can''t attack unless you have 4 or more Team Rocket''s in play.'),
	('Cursed Blast','ability','Once during your turn, you may put 13 damage counters on 1 of your opponent''s Pokemon. If you use this Ability, this Pokemon is Knocked Out.'),
	('Boosted Evolution','ability','As long as this Pokemon is in the Active Spot, it can evolve during your first turn or the turn you play it.'),
	('Skyscraper','ability','Prevent all damage done to this Pokemon by attacks form your opponent''s Pokemon that have Special Energy attached.'),
	('Moon Cleave Star','ability','During your turn, you may put 4 damage counters on 1 of your opponent''s Pokemon. (You can''t use more than 1 VSTAR Power in a game).'),
	('Sun Energy','ability','Once during your turn, you may attach a Psychic Energy card from your discard pile to 1 of your Lunatone.'),
	('Witch''s Domain','ability','Once during your turn, you may move up to 2 damage counters from your Pokemon to your opponent''s Active Pokemon.'),
	('Star Guardian','ability','During your turn, if your opponenet has exactly 1 Prize card remaining, you may choose 1 of your opponent''s Benched Pokemon. They discard that Pokemon and all attached cards. (You can''t use more than 1 VSTAR Power in a game.)'),
	('Team Rocket''s Archer','supporter','You can use this card only if any of your Team Rocket''s Pokemon were Knocked Out during your opponenet''s last turn. Each player shuffles thier hand into their deck. Then, you draw 5 cards, and your opponenet draws 3 cards.'),
	('Team Rocket''s Ariana','supporter','Draw cards until you have 5 cards in your hand. If all of your Pokemon in play are Team Rocket''s Pokemon, draw cards until you have 8 cards in your hand.')
GO

PRINT '*** adding to ElementType Table ***'
GO
INSERT INTO [dbo].[ElementType]
	([ElementTypeID],[Description])
VALUES
	('colorless',''),
	('fire',''),
	('water',''),
	('grass',''),
	('electric',''),
	('ice',''),
	('fighting',''),
	('poison',''),
	('ground',''),
	('flying',''),
	('psychic',''),
	('bug',''),
	('rock',''),
	('ghost',''),
	('dragon',''),
	('dark',''),
	('steel',''),
	('fairy','')
GO

PRINT '*** adding to CollectionType Table ***'
GO
INSERT INTO [dbo].[CollectionType]
	([CollectionTypeID],[Description],[MaxSize])
VALUES
	('user','This is a collection of all the users cards.',100000),
	('Custom','',250),
	('Wishlist','',250),
	('Favorites','',100),
	('Deck','',60)
GO


PRINT '*** adding to PokemonRule Table ***'
GO
INSERT INTO [dbo].[PokemonRule]
	([PokemonRuleID],[Description])
VALUES
	('none','none'),
	('Supporter','You may play only 1 Supporter card during your turn.'),
	('Pokemon-EX','When a Pokemon-EX has been Knocked Out, your opponent takes 2 prize cards.'),
	('Mega Evolution','When 1 of your Pokemon becomes a Mega Evolution Pokemon, your turn ends.'),
	('Primal Reversion','When 1 of your Pokemon becomes primal your turn ends.'),
	('BREAK','Your Pokemon retains the attacks, abilities, weakness, resistance, and retreat cost of its previous evolution.'),
	('Pokemon-GX','When your Pokemon-GX is knocked out, your opponent takes 2 Prize cards.'),
	('TAG TEAM Pokemon-GX','When you TAG TEAM is knocked out, your opponenet takes 3 Prize Cards.'),
	('Prism Star','You can''t have more than 1 prism card with the same name in your deck. If a prism card would go to the discard pile, put it in the Lost Zone instead.'),
	('Pokemon V','When your Pokemon V is knocked out, your opponent takes 2 Prize Cards.'),
	('Pokemon VMAX','When your Pokemon VMAX is knocked out, your opponent takes 3 Prize Cards.'),
	('Pokemon V-UNION','When your Pokemon V-UNION is knocked out, your opponent takes 3 Prize Cards.'),
	('Pokemon VSTAR','When your Pokemon VSTAR is knocked out, your opponent takes 2 Prize Cards.'),
	('Radiant Pokemon','You can''t have more than 1 radiant pokemon in your deck.')
GO 


PRINT '*** adding to Move Table ***'
GO
INSERT INTO [dbo].[Move]
	([Name],[Damage],[Description])
VALUES
	('Shadow Bind',150,'During your opponent''s next turn, the Defending Pokemon can''t retreat.'),
	('Reckless Charge',30,'This Pokemon also does 10 damage to itself.'),
	('Roasting Heat',80,'If your opponent'' Active Pokemon is Burned, this attack does 160 more damage.'),
	('Volcanic Meteor',280,'Discard 2 Energy from this Pokemon.'),
	('Mega Ascension',0,'Search your deck for M Rayquaza-EX, reveal it, and put it into your hand. Shuffle your deck afterward.'),
	('Aeroscream',130,'Flip a coin. If tails, discard 2 Energy attached to this Pokemon.'),
	('Dragon Claw',120,'none'),
	('Sonic Strike',0,'Discard 3 Energy from this Pokemon. This attack does 220 damage to 1 of your opponenet''s Pokemon. (Don''t apply Weakness and Resistance for Benched Pokemon.)'),
	('Gaia Volcano',100,'If there is any Stadium card in play, this attack does 100 more damage. Discaard hat Stadium card.'),
	('Dragon Ascent',300,'Discard 2 Energy attached to this Pokemon.'),
	('Sonic Ace',0,'Discard 2 Energy attached to this Pokemon. This attack does 120 damage to 1 of your opponenet''s Pokemon. (Don''t apply Weakness and Resistance for Benched Pokemon.)'),
	('Wild Blaze',300,'Discard the top 5 of your deck.'),
	('V-Force',120,'If you have 4 or fewer Benched Pokemon, this attack does nothing.'),
	('Heart Stamp',10,'none'),
	('Bite',50,'none'),
	('Snarl',100,'During your opponenet''s next turn, attacks used by the Defending Pokemon do 100 less damage (before applying Weakness and Resistance.)'),
	('Strike Down',0,'If your opponenet''s Actiove Pokemon has 4 or more damage ccounters on it, that Pokemon is Knocked Out.'),
	('Massive Rend',140,'none'),
	('G-Max Pulverization',220,'This attack''s damage isn''t affected by any effects on your opponent''s Active Pokemon.'),
	('Powerful Rage',20,'This attack does 20 damage of each damage counter on this Pokemon.'),
	('Virtuous Flame',170,'none'),
	('Headbutt',10,'none'),
	('Invade',30,'none'),
	('Aura Jab',130,' Attach up to 3 Basic Fighting Energy cards from your discard pile to your Benched Pokemon in any way you like.'),
	('Mega Brave',270,'During your next turn, this Pokemon can''t use Mega Brave.'),
	('Salt Coating',0,'Heal 20 damage from 1 of your Pokemon.'),
	('Tackle',30,'none'),
	('Photon Wave',30,'During your opponent''s next turn, any damage done by attacks from the Defending Pokemon is reduced by 30 (beofre applying Weakness and Resistance).'),
	('Psyburn',120,'none'),
	('Piercing Gaze',120,'Your opponenet reveals their hand. Discard a card you find there.'),
	('Volt Strike',250,'Discard all Energy from this Pokemon.'),
	('Hold Still',0,'Heal 30 damage fro this Pokemon.'),
	('Razor Fin',20,'none'),
	('Skill Dive',0,'This attack does 50 damage to 1 of your opponent''s Pokemon. (Don''t apply Weakness and Resistance for Benched Pokemon).'),
	('Jet Headbutt',110,'none'),
	('Shell Press',10,'During your opponenet''s next turn, this Pokemon takes 10 less damage from attacks (after applying Weakness and Resistance).'),
	('Merciless Blade',110,'If your opponent''s Active Pokemon already has any damage counters on it, this attack does 110 more damage.'),
	('Spinning Attack',50,'none'),
	('Meteor Mash',60,'During your next turn, this Pokemon''s Meteor Mash attack does 60 more damage (before applying Weakness and Resistance).'),
	('Luster Blast',200,'Discard 2 Energy from this Pokemon.'),
	('G-Max Smite',150,'Your opponent''s Active Pokemon is now Confused.'),
	('Giga Impact',230,'During your next turn, this Pokemon can''t attack.')
GO

PRINT '*** adding to MoveCost ***'
GO
INSERT INTO [dbo].[MoveCost]
	([MoveID],[ElementTypeID],[Quantity])
VALUES
	(1,'psychic',2),
	(1,'colorless',1),
	(2,'Colorless',2),
	(3,'fire',1),
	(4,'fire',1),
	(4,'colorless',3),
	(5,'colorless',2),
	(6,'colorless',4),
	(7,'water',1),
	(7,'fighting',1),
	(7,'colorless',1),
	(8,'water',1),
	(8,'fighting',2),
	(8,'colorless',1),
	(9,'fighting',3),
	(9,'colorless',1),
	(10,'fire',3),
	(10,'electric',1),
	(10,'colorless',1),
	(11,'water',1),
	(11,'psychic',1),
	(11,'colorless',1),
	(12,'fire',2),
	(12,'dark',1),
	(12,'colorless',2),
	(13,'fire',2),
	(14,'colorless',1),
	(15,'colorless',2),
	(16,'fire',1),
	(16,'colorless',2),
	(17,'steel',1),
	(18,'steel',1),
	(18,'colorless',2),
	(19,'fighting',1),
	(19,'steel',2),
	(20,'fire',1),
	(20,'electric',1),
	(21,'fire',2),
	(21,'electric',1),
	(21,'colorless',1),
	(22,'dark',1),
	(23,'dark',2),
	(24,'fighting',1),
	(25,'fighting',2),
	(26,'fighting',1),
	(27,'fighting',2),
	(28,'colorless',2),
	(29,'psychic',2),
	(29,'colorless',2),
	(30,'colorless',2),
	(31,'electric',2),
	(32,'water',1),
	(33,'colorless',2),
	(34,'psychic',1),
	(34,'colorless',1),
	(35,'psychic',2),
	(35,'colorless',1),
	(36,'water',1),
	(37,'dark',2),
	(38,'fighting',1),
	(38,'colorless',1),
	(38,'steel',1),
	(39,'steel',1),
	(40,'steel',1),
	(40,'colorless',3),
	(41,'psychic',1),
	(41,'colorless',2),
	(42,'colorless',3)

PRINT '*** adding to Artist Table ***'
GO
INSERT INTO [dbo].[Artist]
	([GivenName],[Surname])
VALUES
	('5ban','graphics'),
	('0313',''),
	('2003 pikachu','project'),
	('2004 pikachu','project'),
	('2005 pikachu','project'),
	('2006 pikachu','project'),
	('2009 pikachu','project'),
	('2014 pikachu','project'),
	('2017 pikachu','project'),
	('2018 pikachu','project'),
	('2019 pikachu','project'),
	('2020 pikachu','project'),
	('ack cg','works'),
	('acorviart',''),
	('adidas enjin','project'),
	('ai','kurihara'),
	('aimi','tomita'),
	('akagi',''),
	('akino','fukuji'),
	('akira','egawa'),
	('akira','komayama'),
	('aky cg','works'),
	('aliya','chen'),
	('amelicart',''),
	('anderson',''),
	('anesaki','dynamic'),
	('aoki',''),
	('apios',''),
	('arai','kiriko'),
	('asako','ito'),
	('aspara',''),
	('asuka','iwashita'),
	('atsuko','nishida'),
	('atsuko','ujiie'),
	('atsushi','furusawa'),
	('atsuya','uki'),
	('avec','yoko'),
	('ayaka','yoshida'),
	('ayako','ozaki'),
	('aya','kusube'),
	('ayoka','yoshida'),
	('ayumi','odashima'),
	('benimaru','itoh'),
	('beruburi',''),
	('big mama','tagawa'),
	('booota',''),
	('buchi',''),
	('bun','toujo'),
	('burari',''),
	('chibi',''),
	('christopher','rush'),
	('cochi8i',''),
	('cona','nitanda'),
	('conceptlab',''),
	('craig','turvey'),
	('cr cg','gangs'),
	('d.a.g','inc.'),
	('daisuke','ito'),
	('daisuke','iwamoto'),
	('daisuke','ochiai'),
	('danciao',''),
	('demizuposuka',''),
	('dom',''),
	('dr.ooyama',''),
	('dsuke',''),
	('ebila',''),
	('emi','ando'),
	('emi','miwa'),
	('emi','yoshida'),
	('en','morikura'),
	('eri','kamei'),
	('eri','yamaki'),
	('eske','yoshinob'),
	('etsuya','hattori'),
	('felicia','chen'),
	('framestore',''),
	('fujimoto','gold'),
	('fumie','kittaka'),
	('fuzichoco',''),
	('gakuji','nomoto'),
	('game freak','inc.'),
	('gapao',''),
	('gemi',''),
	('gidora',''),
	('ginga',''),
	('gogotake',''),
	('gosho','aoyama'),
	('gossan',''),
	('goto','minori'),
	('hagiya','kaoru'),
	('hajime','kusajima'),
	('hanabushi',''),
	('hanako',''),
	('haru','akasaka'),
	('haruko','ichikawa'),
	('hasegawa','saki'),
	('hasuno',''),
	('hatachu',''),
	('hataya',''),
	('heisuke','kitazawa'),
	('hico','kim'),
	('hideaki','hakozaki'),
	('hideki','ishikawa'),
	('hideki','kazama'),
	('hideyuki','nakajima'),
	('hiiroki','asanuma'),
	('hikaru','koike'),
	('hiranobu','uoshida'),
	('hiroaki','ito'),
	('hiroki','asanuma'),
	('hiroki','fuchino'),
	('hiromichi','sugiyama'),
	('hiron',''),
	('hironobu','yoshida'),
	('hirotaka','marufuji'),
	('hiroyuki','yamamoto'),
	('hisao','nakamura'),
	('hitoshi','ariga'),
	('hizuki','misono'),
	('hncl',''),
	('hoshino','kuro'),
	('huang tzu','en'),
	('hyogonosuke',''),
	('ikeda','saki'),
	('imakuni',''),
	('imakunki',''),
	('imoniii',''),
	('inose','yukie'),
	('iori','suzuki'),
	('ito','kyoko'),
	('ito','kyoto'),
	('iwaiya',''),
	('iwamoto05',''),
	('izucch',''),
	('james','turner'),
	('jerky',''),
	('jiro','sasumo'),
	('jiro','sasuno'),
	('julie','hang'),
	('jumpei','akasaka'),
	('jungo','suzuki'),
	('junsei','kuninobu'),
	('k.','hoshiba'),
	('k.','utsunomiya'),
	('kadama',''),
	('kagemaru','himeno'),
	('kai','ishikawa'),
	('kamome','shirahama'),
	('kamonabe',''),
	('kanahei',''),
	('kanako','eo'),
	('kanami','ogata'),
	('kantaro',''),
	('kariya',''),
	('kasumi','matsuda'),
	('katsunori','sato'),
	('katsura','tabata'),
	('kawayoo',''),
	('kazuaki','aihara'),
	('kazuhiko','nishihara'),
	('kazuki','minami'),
	('kazuma','koda'),
	('kazumasa','yasukuni'),
	('kazuo','yazawa'),
	('kazuyuki','kano'),
	('kedamahadaitai','yawarakai'),
	('kei','hoshinba'),
	('keiichiro','ito'),
	('keiji','kinebuchi'),
	('keiko','fukuyama'),
	('keiko','moritsugu'),
	('keisin',''),
	('keita','komatsuya'),
	('keita','takahashi'),
	('ken','ikuji'),
	('kenkichi','toyama'),
	('ken','sugimori'),
	('kent','kanetsuna'),
	('kg-2000',''),
	('k','hoshiba'),
	('kimiya','masago'),
	('kinu','nishimura'),
	('kirisaki',''),
	('kiyotaka','oshiyama'),
	('kodama',''),
	('koji','nakata'),
	('kouji','tajima'),
	('kouki','saitou'),
	('krgc',''),
	('kunihiko','yuyama'),
	('kurata','so'),
	('kuroimori',''),
	('kurumitsu',''),
	('kyoko','koizumi'),
	('kyoko','umemoto'),
	('kyupiyama',''),
	('lee','hyunjung'),
	('lee','mina'),
	('ligton',''),
	('linne',''),
	('m.','akiyama'),
	('mahou',''),
	('maiko','fujiwara'),
	('makato','mizobuchi'),
	('makoto','imai'),
	('makoto','mizobuchi'),
	('makura','tami'),
	('mame','akimaru'),
	('mana','ibe'),
	('marina','chikazawa'),
	('masa',''),
	('masahiko','ishii'),
	('masakazu','fukuda'),
	('masako','tomii'),
	('masako','yamashita'),
	('mashu',''),
	('maskazu','fukuda'),
	('matazo',''),
	('match',''),
	('matofumi','fujiwara'),
	('mazakaza','fukuda'),
	('megumi','higuchi'),
	('megumi','mizutani'),
	('mekayu',''),
	('mele',''),
	('midori','harada'),
	('miho','asada'),
	('mika','pikazo'),
	('mikiko','takeda'),
	('miki','kudo'),
	('mikio','menjo'),
	('miki','tanak'),
	('miki','tanaka'),
	('milky','isobe'),
	('minahamu',''),
	('minaminami','take'),
	('mina','nakai'),
	('minato',''),
	('mingo',''),
	('mio','muroi'),
	('miranda','branley'),
	('misaki','hashimoto'),
	('misaki','hasimoto'),
	('misa','tsutsui'),
	('mitsuhiro','arita'),
	('mizue',''),
	('mori','yuu'),
	('motofumi','fujiwara'),
	('mousho',''),
	('mpc','film'),
	('mt.','tbt'),
	('mugenup',''),
	('mugi','hamada'),
	('n-design','inc.'),
	('nabana','kensaku'),
	('nabatame','kazutaka'),
	('nagano',''),
	('nagimiso',''),
	('nagomi','nijo'),
	('nakamura','ippan'),
	('nakano','satoshi'),
	('nakaoka',''),
	('naoki','saito'),
	('naoyo','kimura'),
	('narano',''),
	('narumi','sato'),
	('natsuko shinji','ete'),
	('natsumi','miyanose'),
	('natsumi','yoshida'),
	('natsumi','yoshisda'),
	('nc','empire'),
	('n design','inc.'),
	('nelnal',''),
	('nisimono',''),
	('nisota','niso'),
	('noboyuki','hobu'),
	('nobuhiro','imagawa'),
	('nobuyuki','fujimoto'),
	('nobuyuki','habu'),
	('noriko','hotta'),
	('noriko','takaya'),
	('noriko','uono'),
	('nousawa','mochipuyo'),
	('nurikabe',''),
	('okacheke',''),
	('okayamatakatoshi',''),
	('oku',''),
	('okubo',''),
	('ooyama',''),
	('orbitallink','inc.'),
	('orca',''),
	('osare',''),
	('oswaldo','kato'),
	('otumami',''),
	('ounishi',''),
	('pani','kobayashi'),
	('pikamania',''),
	('planeta',''),
	('planeta','hiiragi'),
	('planeta','igarashi'),
	('planeta','mochizuiki'),
	('planeta','mochizuki'),
	('planeta','otani'),
	('planeta','tsuji'),
	('planeta','yamashita'),
	('po-suzuki',''),
	('pokemon get','tv'),
	('pokemon','rumble'),
	('q-rais',''),
	('raita','kazama'),
	('reiko','tanoue'),
	('rend',''),
	('reospikee',''),
	('rianti','hidayat'),
	('rika',''),
	('rina',''),
	('rond',''),
	('ryoma','uratsuka'),
	('ryota','muramasa'),
	('ryota','murayama'),
	('ryota','saito'),
	('ryo','ueda'),
	('ryuta','fuse'),
	('ryuta','kusumi'),
	('saboteri',''),
	('sachiko','adachi'),
	('sachiko','eba'),
	('sachi','matoba'),
	('sadaji',''),
	('saino','misaki'),
	('saki','hayashiro'),
	('sakiko','maeda'),
	('saki','yahashiro'),
	('sanosuke','sakuma'),
	('satoma',''),
	('satoshi','nakai'),
	('satoshi','ohta'),
	('satoshi','shirai'),
	('satoshi','yamamoto'),
	('sayaka','maruyama'),
	('saya','tsuruta'),
	('sayuri','ichiishi'),
	('scav',''),
	('sekio',''),
	('shiburingaru',''),
	('shibuzoh.',''),
	('shigenori','negishi'),
	('shimaris','yukichi'),
	('shimeris','yukichi'),
	('shin-ichi','yoshida'),
	('shin-ichi','yoshikawa'),
	('shinji','higuchi'),
	('shinji','kanda'),
	('shin','nagasawa'),
	('shinya','komatsu'),
	('shinya','mazuno'),
	('shinya','mizuno'),
	('shizurow',''),
	('shoko','nakagawa'),
	('sie','nanahara'),
	('siwama','chiaki'),
	('so-taro',''),
	('souchirou','gunjima'),
	('souichirou','gunjima'),
	('sowsow',''),
	('spike','chunsoft.'),
	('studio bora','inc'),
	('studio bora','inc.'),
	('sui',''),
	('sumiyoshi','kitzuki'),
	('sumiyoshi','kizuki'),
	('susumu','maeya'),
	('suwama','chiaki'),
	('svlt',''),
	('t.','honda'),
	('taiga','kasai'),
	('taiga','kayama'),
	('taira','akitsu'),
	('takabon',''),
	('takahiro','yamashita'),
	('takao','unno'),
	('takashi','shiraishi'),
	('takashi','yamaguchi'),
	('take',''),
	('takeshia','nakamura'),
	('takeshi','nakamura'),
	('takumi','akabane'),
	('takumi','wada'),
	('takuyoa',''),
	('teeziro',''),
	('tekashi','shiraishi'),
	('terada','tera'),
	('tetsu','kayama'),
	('tetsuo','hara'),
	('tetsuo','yajima'),
	('tetsuya','koizumi'),
	('pokemon company','art team'),
	('tika','matsuno'),
	('tika','matusno'),
	('toi8',''),
	('tokichan',''),
	('tokiya',''),
	('tokumi','akabane'),
	('tomiyasu','daiki'),
	('tomoaki','imakuni'),
	('tomohiro','kitakaze'),
	('tomokazu','komiya'),
	('tomoko','wakai'),
	('tomomi','kaneko'),
	('tomomi','ozaki'),
	('tomomo','ozaki'),
	('tomowaka',''),
	('tonji','matsuno'),
	('tono',''),
	('toriyufu',''),
	('toshinao','aoki'),
	('toyste',''),
	('toyste','beach'),
	('tsuyoshi','nagano'),
	('uninori',''),
	('usgmen',''),
	('uta',''),
	('wataru','kawahara'),
	('whisker',''),
	('wintr','wandr'),
	('y.','fujishima'),
	('yamazaki','rei'),
	('yano','keiji'),
	('yashiro','nanaco'),
	('yasuda','shuhei'),
	('yasuki','watanabe'),
	('yoichi','katabe'),
	('yoko','hishida'),
	('yoriuki','ikegami'),
	('yoriyuki','ikegami'),
	('yoshimi','miyoshi'),
	('yoshinobu','saito'),
	('yoshioka',''),
	('yosuke da','silva'),
	('you','iribi'),
	('yousuke','hirata'),
	('yuichi','sawayama'),
	('yuka','morii'),
	('yuka','tanaka'),
	('yukihiro','tada'),
	('yukiko','baba'),
	('yumi',''),
	('yu','nagaba'),
	('yuriko','akase'),
	('yuri','umemura'),
	('yusuke','ishikawa'),
	('yusuke','kozaki'),
	('yusuke','ohmura'),
	('yusuke','shimada'),
	('yuu',''),
	('yuuki','kawamura'),
	('yuu','nishida'),
	('yuya','oka'),
	('zig',''),
	('zu-ka','')
GO

print '*** adding to Series Table ***'
GO
INSERT INTO [dbo].[Series]
	([SeriesID],[BoosterCount],[ReleaseDate],[ImagePath],[Active])
VALUES
	('Original Series',7,'1999-01-09','/pokemon/series/Original-Series-logo.webp',1),
	('Neo Series',4,'2000-12-16','/pokemon/series/Neo-Genesis-logo.webp',1),
	('Legendary Collection',1,'2002-05-24','/pokemon/series/Legendary-Collection-logo.webp',1),
	('e-Card',3,'2002-09-15','/pokemon/series/e-Card-logo.webp',1),
	('Ex',16,'2003-07-18','/pokemon/series/Ex-logo.webp',1),
	('Diamond & Pearl',7,'2007-05-23','/pokemon/series/Diamond-Pearl-logo.webp',1),
	('Platinum',4,'2009-02-11','/pokemon/series/Platinum-logo.webp',1),
	('HeartGold & SoulSilver',4,'2010-02-10','/pokemon/series/HeartGold-SoulSilver-logo.webp',1),
	('Call of Legends',1,'2011-02-09','/pokemon/series/Call-of-Legends-logo.webp',1),
	('Black & White',12,'2011-02-25','/pokemon/series/Black-White-logo.webp',1),
	('XY',15,'2013-11-08','/pokemon/series/XY-logo.webp',1),
	('Sun & Moon',16,'2017-02-03','/pokemon/series/Sun-Moon-logo.webp',1),
	('Sword & Shield',17,'2020-02-07','/pokemon/series/Sword-Shield-logo.webp',1),
	('Scarlet & Violet',16,'2023-03-31','/pokemon/series/Scarlet-Violet-logo.webp',1),
	('Mega Evolution',5,'2025-09-26','/pokemon/series/Mega-Evolution-logo.webp',1),
	('Black Star',10,'1999-07-01','/pokemon/series/Black-Star-logo.png',1),
	('McDonald''s Collection',14,'2011-06-17','/pokemon/series/McDonalds-logo.webp',1),
	('Trick or Trade',4,'2022-09-01','/pokemon/series/Trick-Or-Trade-logo.webp',1),
	('POP',9,'2004-09-01','/pokemon/series/POP-logo.webp',1),
	('Play! Pokemon Prize Pack',7,'2022-11-09','/pokemon/series/Play-Pokemon-Prize-Pack-logo.png',1),
	('Miscellaneous',5,'1999-01-01','/pokemon/series/Miscellaneous-logo.png',1)
GO

PRINT '*** adding to Booster Table ***'
GO
INSERT INTO [dbo].[Booster]
	([BoosterID],[SeriesID],[ReleaseDate],[Abbreviation],
	 [BaseCount],[SecretCount],[TotalCount],
	 [Active],[IsFull],[LogoPath],[SymbolPath])
VALUES
	('Base Set','Original Series','1999-01-09','bs',102,0,102,1,0,'/pokemon/boosters/Base-Set-logo.webp','none'),
	('Jungle','Original Series','1999-06-16','ju',64,0,64,1,0,'/pokemon/boosters/Jungle-logo.webp','/pokemon/boosters/Jungle-symbol.webp'),
	('Fossil','Original Series','1999-10-10','fo',62,0,62,1,0,'/pokemon/boosters/Fossil-logo.webp','/pokemon/boosters/Fossil-symbol.webp'),
	('Base Set 2','Original Series','2000-02-24','b2',130,0,130,1,0,'/pokemon/boosters/Base-Set-2-logo.webp','/pokemon/boosters/Base-Set-2-symbol.webp'),
	('Team Rocket','Original Series','2000-04-24','tr',82,1,83,1,0,'/pokemon/boosters/Team-Rocket-logo.webp','/pokemon/boosters/Team-Rocket-symbol.webp'),
	('Gym Heroes','Original Series','2000-08-14','g1',132,0,132,1,0,'/pokemon/boosters/Gym-Heroes-logo.webp','/pokemon/boosters/Gym-Heroes-symbol.webp'),
	('Gym Challenge','Original Series','2000-10-16','g2',132,0,132,1,0,'/pokemon/boosters/Gym-Challenge-logo.webp','/pokemon/boosters/Gym-Challenge-symbol.webp'),
	
	('Neo Genesis','Neo Series','2000-12-16','n1',111,0,111,1,0,'/pokemon/boosters/Neo-Genesis-logo.webp','/pokemon/boosters/Neo-Genesis-symbol.webp'),
	('Neo Discovery','Neo Series','2001-06-01','n2',75,0,75,1,0,'/pokemon/boosters/Neo-Discovery-logo.webp','/pokemon/boosters/Neo-Discovery-symbol.webp'),
	('Neo Revelation','Neo Series','2001-09-21','n3',64,2,66,1,0,'/pokemon/boosters/Neo-Revelation-logo.webp','/pokemon/boosters/Neo-Revelation-symbol.webp'),
	('Neo Destiny','Neo Series','2002-02-28','n4',105,8,113,1,0,'/pokemon/boosters/Neo-Destiny-logo.webp','/pokemon/boosters/Neo-Destiny-symbol.webp'),
	
	('Legendary Collection','Legendary Collection','2002-05-24','lc',110,0,110,1,0,'/pokemon/boosters/Legendary-Collection-logo.webp','/pokemon/boosters/Legendary-Collection-symbol.png'),
	
	('Expedition Base Set','e-Card','2002-09-15','ex',165,0,165,1,0,'/pokemon/boosters/Expedition-Base-Set-logo.webp','/pokemon/boosters/Expedition-Base-Set-symbol.png'),
	('Aquapolis','e-Card','2003-01-15','aq',147,35,182,1,0,'/pokemon/boosters/Aquapolis-logo.webp','/pokemon/boosters/Aquapolis-symbol.webp'),
	('Skyridge','e-Card','2003-05-12','sk',144,38,182,1,0,'/pokemon/boosters/Skyridge-logo.webp','/pokemon/boosters/Skyridge-symbol.webp'),
	
	('Ruby & Sapphire','Ex','2003-07-18','rs',109,0,109,1,0,'/pokemon/boosters/Ruby-Sapphire-logo.webp','/pokemon/boosters/Ruby-Sapphire-symbol.webp'),
	('Sandstorm','Ex','2003-09-18','ss',100,0,100,1,0,'/pokemon/boosters/Sandstorm-logo.webp','/pokemon/boosters/Sandstorm-symbol.webp'),
	('Dragon','Ex','2003-11-24','dr',97,3,100,1,0,'/pokemon/boosters/Dragon-logo.webp','/pokemon/boosters/Dragon-symbol.webp'),
	('Team Magma vs Team Aqua','Ex','2004-03-15','ma',95,2,97,1,0,'/pokemon/boosters/Team-Magma-vs-Team-Aqua-logo.webp','/pokemon/boosters/Team-Magma-vs-Team-Aqua-symbol.webp'),
	('Hidden Legends','Ex','2004-07-14','hl',101,1,102,1,0,'/pokemon/boosters/Hidden-Legends-logo.webp','/pokemon/boosters/Hidden-Legends-symbol.webp'),
	('FireRed & LeafGreen','Ex','2004-08-30','rg',112,4,116,1,0,'/pokemon/boosters/FireRed-LeafGreen-logo.webp','/pokemon/boosters/FireRed-LeafGreen-symbol.webp'),
	('Team Rocket Returns','Ex','2004-11-08','trr',109,2,111,1,0,'/pokemon/boosters/Team-Rocket-Returns-logo.webp','/pokemon/boosters/Team-Rocket-Returns-symbol.webp'),
	('Deoxys','Ex','2005-02-14','dx',107,1,108,1,0,'/pokemon/boosters/Deoxys-logo.webp','/pokemon/boosters/Deoxys-symbol.webp'),
	('Emerald','Ex','2005-05-09','em',106,1,107,1,0,'/pokemon/boosters/Emerald-logo.webp','/pokemon/boosters/Emerald-symbol.webp'),
	('Unseen Forces','Ex','2005-08-22','uf',115,29,144,1,0,'/pokemon/boosters/Unseen-Forces-logo.webp','/pokemon/boosters/Unseen-Forces-symbol.webp'),
	('Delta Species','Ex','2005-10-31','ds',113,1,114,1,0,'/pokemon/boosters/Delta-Species-logo.webp','/pokemon/boosters/Delta-Species-symbol.webp'),
	('Legend Maker','Ex','2006-02-13','lm',92,1,93,1,0,'/pokemon/boosters/Legend-Maker-logo.webp','/pokemon/boosters/Legend-Maker-symbol.webp'),
	('Holon Phantoms','Ex','2006-05-03','hp',110,1,111,1,0,'/pokemon/boosters/Holon-Phantoms-logo.webp','/pokemon/boosters/Holon-Phantoms-symbol.webp'),
	('Crystal Guardians','Ex','2006-08-30','cg',100,0,100,1,0,'/pokemon/boosters/Crystal-Guardians-logo.webp','/pokemon/boosters/Crystal-Guardians-symbol.webp'),
	('Dragon Frontiers','Ex','2006-11-08','df',101,0,101,1,0,'/pokemon/boosters/Dragon-Frontiers-logo.webp','/pokemon/boosters/Dragon-Frontiers-symbol.webp'),
	('Power Keepers','Ex','2007-02-14','pk',108,0,108,1,0,'/pokemon/boosters/Power-Keepers-logo.webp','/pokemon/boosters/Power-Keepers-symbol.webp'),
	
	('Diamond & Pearl','Diamond & Pearl','2007-05-23','dp',130,0,130,1,0,'/pokemon/boosters/Diamond-Pearl-logo.webp','/pokemon/boosters/Diamond-Pearl-symbol.webp'),
	('Mysterious Treasures','Diamond & Pearl','2007-08-22','mt',123,1,124,1,0,'/pokemon/boosters/Mysterious-Treasures-logo.webp','/pokemon/boosters/Mysterious-Treasures-symbol.webp'),
	('Secret Wonders','Diamond & Pearl','2007-11-07','sw',132,0,132,1,0,'/pokemon/boosters/Secret-Wonders-logo.webp','/pokemon/boosters/Secret-Wonders-symbol.webp'),
	('Great Encounters','Diamond & Pearl','2008-02-13','ge',106,0,106,1,0,'/pokemon/boosters/Great-Encounters-logo.webp','/pokemon/boosters/Great-Encounters-symbol.webp'),
	('Majestic Dawn','Diamond & Pearl','2008-05-21','md',100,0,100,1,0,'/pokemon/boosters/Majestic-Dawn-logo.webp','/pokemon/boosters/Majestic-Dawn-symbol.webp'),
	('Legends Awakened','Diamond & Pearl','2008-08-20','la',146,0,146,1,0,'/pokemon/boosters/Legends-Awakened-logo.webp','/pokemon/boosters/Legends-Awakened-symbol.webp'),
	('Stormfront','Diamond & Pearl','2008-11-05','sf',100,6,106,1,0,'/pokemon/boosters/Stormfront-logo.webp','/pokemon/boosters/Stormfront-symbol.webp'),
	
	('Platinum','Platinum','2009-02-11','pl',127,6,133,1,0,'/pokemon/boosters/Platinum-logo.webp','/pokemon/boosters/Platinum-symbol.webp'),
	('Rising Rivals','Platinum','2009-05-16','rr',111,9,120,1,0,'/pokemon/boosters/Rising-Rivals-logo.webp','/pokemon/boosters/Rising-Rivals-symbol.webp'),
	('Supreme Victors','Platinum','2009-08-19','sv',147,6,153,1,0,'/pokemon/boosters/Supreme-Victors-logo.webp','/pokemon/boosters/Supreme-Victors-symbol.webp'),
	('Arceus','Platinum','2009-11-04','ar',99,12,111,1,0,'/pokemon/boosters/Arceus-logo.webp','/pokemon/boosters/Arceus-symbol.webp'),
	
	('HeartGold & SoulSilver','HeartGold & SoulSilver','2010-02-10','hs',123,1,124,1,0,'/pokemon/boosters/HeartGold-SoulSilver-logo.webp','/pokemon/boosters/HeartGold-SoulSilver-symbol.webp'),
	('Unleashed','HeartGold & SoulSilver','2010-05-12','ul',95,1,96,1,0,'/pokemon/boosters/Unleashed-logo.webp','/pokemon/boosters/Unleashed-symbol.webp'),
	('Undaunted','HeartGold & SoulSilver','2010-08-18','ud',90,1,91,1,0,'/pokemon/boosters/Undaunted-logo.webp','/pokemon/boosters/Undaunted-symbol.webp'),
	('Triumphant','HeartGold & SoulSilver','2010-11-03','tm',102,1,103,1,0,'/pokemon/boosters/Triumphant-logo.webp','/pokemon/boosters/Triumphant-symbol.webp'),
	
	('Call of Legends','Call of Legends','2011-02-09','cl',95,11,106,1,0,'/pokemon/boosters/Call-of-Legends-logo.webp','/pokemon/boosters/Call-of-Legends-symbol.webp'),
	
	('Black & White','Black & White','2011-04-25','blw',114,2,116,1,0,'/pokemon/boosters/Black-White-logo.webp','/pokemon/boosters/Black-White-symbol.webp'),
	('Emerging Powers','Black & White','2011-08-31','epo',98,0,98,1,0,'/pokemon/boosters/Emerging-Powers-logo.webp','/pokemon/boosters/Emerging-Powers-symbol.webp'),
	('Noble Victories','Black & White','2011-11-16','nvi',101,1,102,1,0,'/pokemon/boosters/Noble-Victories-logo.webp','/pokemon/boosters/Noble-Victories-symbol.webp'),
	('Next Destinies','Black & White','2012-02-08','nxd',99,4,103,1,0,'/pokemon/boosters/Next-Destinies-logo.webp','/pokemon/boosters/Next-Destinies-symbol.webp'),
	('Dark Explorers','Black & White','2012-05-09','dex',108,3,111,1,0,'/pokemon/boosters/Dark-Explorers-logo.webp','/pokemon/boosters/Dark-Explorers-symbol.webp'),
	('Dragons Exalted','Black & White','2012-08-15','drx',124,4,128,1,0,'/pokemon/boosters/Dragons-Exalted-logo.webp','/pokemon/boosters/Dragons-Exalted-symbol.webp'),
	('Dragon Vault','Black & White','2012-10-05','drv',20,1,21,1,0,'/pokemon/boosters/Dragon-Vault-logo.webp','/pokemon/boosters/Dragon-Vault-symbol.webp'),
	('Boundaries Crossed','Black & White','2012-11-07','bcr',149,4,153,1,0,'/pokemon/boosters/Boundaries-Crossed-logo.webp','/pokemon/boosters/Boundaries-Crossed-symbol.webp'),
	('Plasma Storm','Black & White','2013-02-06','pls',135,3,138,1,0,'/pokemon/boosters/Plasma-Storm-logo.webp','/pokemon/boosters/Plasma-Storm-symbol.webp'),
	('Plasma Freeze','Black & White','2013-05-08','plf',116,6,122,1,0,'/pokemon/boosters/Plasma-Freeze-logo.webp','/pokemon/boosters/Plasma-Freeze-symbol.webp'),
	('Plasma Blast','Black & White','2013-08-14','plb',101,5,106,1,0,'/pokemon/boosters/Plasma-Blast-logo.webp','/pokemon/boosters/Plasma-Blast-symbol.webp'),
	('Legendary Treasures','Black & White','2013-11-06','ltr',113,27,140,1,0,'/pokemon/boosters/Legendary-Treasures-logo.webp','/pokemon/boosters/Legendary-Treasures-symbol.webp'),
	
	('Evolutions','XY','2016-11-02','evo',108,5,113,1,0,'/pokemon/boosters/Evolutions-logo.webp','/pokemon/boosters/Evolutions-symbol.webp'),
	('Steam Siege','XY','2016-08-03','sts',114,2,116,1,0,'/pokemon/boosters/Steam-Siege-logo.webp','/pokemon/boosters/Steam-Siege-symbol.webp'),
	('Fates Collide','XY','2016-05-02','fco',124,1,125,1,0,'/pokemon/boosters/Fates-Collide-logo.webp','/pokemon/boosters/Fates-Collide-symbol.webp'),
	('Generations','XY','2016-02-22','gen',83,0,83,1,0,'/pokemon/boosters/Generations-logo.webp','/pokemon/boosters/Generations-symbol.webp'),
	('BREAKpoint','XY','2016-02-03','bkp',122,1,123,1,0,'/pokemon/boosters/Breakpoint-logo.webp','/pokemon/boosters/Breakpoint-symbol.webp'),
	('BREAKthrough','XY','2015-11-04','bkt',162,2,164,1,0,'/pokemon/boosters/Breakthrough-logo.webp','/pokemon/boosters/Breakthrough-symbol.webp'),
	('Ancient Origins','XY','2015-08-12','aor',98,2,100,1,0,'/pokemon/boosters/Ancient-Origins-logo.webp','/pokemon/boosters/Ancient-Origins-symbol.webp'),
	('Roaring Skies','XY','2015-05-06','ros',108,2,110,1,0,'/pokemon/boosters/Roaring-Skies-logo.webp','/pokemon/boosters/Roaring-Skies-symbol.webp'),
	('Double Crisis','XY','2015-03-25','dcr',34,0,34,1,0,'/pokemon/boosters/Double-Crisis-logo.webp','/pokemon/boosters/Double-Crisis-symbol.webp'),
	('Primal Clash','XY','2015-02-04','prc',160,4,164,1,0,'/pokemon/boosters/Primal-Clash-logo.webp','/pokemon/boosters/Primal-Clash-symbol.webp'),
	('Phantom Forces','XY','2014-11-05','phf',119,0,119,1,0,'/pokemon/boosters/Phantom-Forces-logo.webp','/pokemon/boosters/Phantom-Forces-symbol.webp'),
	('Furious Fists','XY','2014-08-13','ffi',111,2,113,1,0,'/pokemon/boosters/Furious-Fists-logo.webp','/pokemon/boosters/Furious-Fists-symbol.webp'),
	('Flashfire','XY','2014-05-07','flf',106,3,109,1,0,'/pokemon/boosters/Flashfire-logo.webp','/pokemon/boosters/Flashfire-symbol.webp'),
	('XY','XY','2014-02-05','xy',146,0,146,1,0,'/pokemon/boosters/XY-logo.webp','/pokemon/boosters/XY-symbol.webp'),
	('Kalos Starter Set','XY','2013-11-08','kss',45,0,45,1,0,'/pokemon/boosters/Kalos-Starter-Set-logo.webp','/pokemon/boosters/Kalos-Starter-Set-symbol.webp'), 
	
	('Cosmic Eclipse','Sun & Moon','2019-11-01','cec',236,35,271,1,0,'/pokemon/boosters/Cosmic-Eclipse-logo.webp','/pokemon/boosters/Cosmic-Eclipse-symbol.webp'),
	('Hidden Fates','Sun & Moon','2019-08-23','hif',68,1,69,1,0,'/pokemon/boosters/Hidden-Fates-logo.webp','/pokemon/boosters/Hidden-Fates-symbol.webp'),
	('Unified Minds','Sun & Moon','2019-08-02','unm',236,22,258,1,0,'/pokemon/boosters/Unified-Minds-logo.webp','/pokemon/boosters/Unified-Minds-symbol.webp'),
	('Unbroken Bonds','Sun & Moon','2019-05-03','unb',214,21,235,1,0,'/pokemon/boosters/Unbroken-Bonds-logo.webp','/pokemon/boosters/Unbroken-Bonds-symbol.webp'),
	('Detective Pikachu','Sun & Moon','2019-04-29','det',18,0,18,1,0,'/pokemon/boosters/Detective-Pikachu-logo.webp','/pokemon/boosters/Detective-Pikachu-symbol.webp'),
	('Team Up','Sun & Moon','2019-02-01','teu',181,15,196,1,0,'/pokemon/boosters/Team-Up-logo.webp','/pokemon/boosters/Team-Up-symbol.webp'),
	('Lost Thunder','Sun & Moon','2018-11-02','lot',214,22,236,1,0,'/pokemon/boosters/Lost-Thunder-logo.webp','/pokemon/boosters/Lost-Thunder-symbol.webp'),
	('Dragon Majesty','Sun & Moon','2018-09-07','drm',70,8,78,1,0,'/pokemon/boosters/Dragon-Majesty-logo.webp','/pokemon/boosters/Dragon-Majesty-symbol.webp'),
	('Celestial Storm','Sun & Moon','2018-08-03','ces',168,15,183,1,0,'/pokemon/boosters/Celestial-Storm-logo.webp','/pokemon/boosters/Celestial-Storm-symbol.webp'),
	('Forbidden Light','Sun & Moon','2018-05-04','fli',131,15,146,1,0,'/pokemon/boosters/Forbidden-Light-logo.webp','/pokemon/boosters/Forbidden-Light-symbol.webp'),
	('Ultra Prism','Sun & Moon','2018-02-02','upr',156,17,173,1,0,'/pokemon/boosters/Ultra-Prism-logo.webp','/pokemon/boosters/Ultra-Prism-symbol.webp'),
	('Crimson Invasion','Sun & Moon','2017-11-03','cin',111,13,124,1,0,'/pokemon/boosters/Crimson-Invasion-logo.webp','/pokemon/boosters/Crimson-Invasion-symbol.webp'),
	('Shining Legends','Sun & Moon','2017-10-06','slg',73,5,78,1,0,'/pokemon/boosters/Shining-Legends-logo.webp','/pokemon/boosters/Shining-Legends-symbol.webp'),
	('Burning Shadows','Sun & Moon','2017-08-04','bus',147,22,169,1,0,'/pokemon/boosters/Burning-Shadows-logo.webp','/pokemon/boosters/Burning-Shadows-symbol.webp'),
	('Guardians Rising','Sun & Moon','2017-05-05','gri',145,24,169,1,0,'/pokemon/boosters/Guardians-Rising-logo.webp','/pokemon/boosters/Guardians-Rising-symbol.webp'),
	('Sun & Moon','Sun & Moon','2017-02-03','sum',149,14,163,1,0,'/pokemon/boosters/Sun-Moon-logo.webp','/pokemon/boosters/Sun-Moon-symbol.webp'), 
	
	('Crown Zenith','Sword & Shield','2023-01-20','crz',159,51,210,1,0,'/pokemon/boosters/Crown-Zenith-logo.webp','/pokemon/boosters/Crown-Zenith-symbol.webp'),
	('Silver Tempest','Sword & Shield','2022-11-11','sit',195,50,245,1,0,'/pokemon/boosters/Silver-Tempest-logo.webp','/pokemon/boosters/Silver-Tempest-symbol.webp'),
	('Lost Origin','Sword & Shield','2022-09-09','lor',196,51,247,1,0,'/pokemon/boosters/Lost-Origin-logo.webp','/pokemon/boosters/Lost-Origin-symbol.webp'),
	('Pokemon Go','Sword & Shield','2022-07-01','pgo',78,10,88,1,0,'/pokemon/boosters/Pokemon-Go-logo.webp','/pokemon/boosters/Pokemon-Go-symbol.webp'),
	('Astral Radiance','Sword & Shield','2022-05-27','asr',189,57,246,1,0,'/pokemon/boosters/Astral-Radiance-logo.webp','/pokemon/boosters/Astral-Radiance-symbol.webp'),
	('Brilliant Stars','Sword & Shield','2022-02-25','brs',172,45,217,1,0,'/pokemon/boosters/Brilliant-Stars-logo.webp','/pokemon/boosters/Brilliant-Stars-symbol.webp'),
	('Fusion Strike','Sword & Shield','2021-11-12','fst',264,20,284,1,0,'/pokemon/boosters/Fusion-Strike-logo.webp','/pokemon/boosters/Fusion-Strike-symbol.webp'),
	('Celebrations','Sword & Shield','2021-10-08','cel',25,0,25,1,0,'/pokemon/boosters/Celebrations-logo.webp','/pokemon/boosters/Celebrations-symbol.webp'),
	('Evolving Skies','Sword & Shield','2021-08-27','evs',203,34,237,1,0,'/pokemon/boosters/Evolving-Skies-logo.webp','/pokemon/boosters/Evolving-Skies-symbol.webp'),
	('Chilling Reign','Sword & Shield','2021-06-18','cre',198,35,233,1,0,'/pokemon/boosters/Chilling-Reign-logo.webp','/pokemon/boosters/Chilling-Reign-symbol.webp'),
	('Battle Styles','Sword & Shield','2021-04-19','bst',163,20,183,1,0,'/pokemon/boosters/Battle-Styles-logo.webp','/pokemon/boosters/Battle-Styles-symbol.webp'),
	('Shining Fates','Sword & Shield','2021-02-19','shf',72,1,73,1,0,'/pokemon/boosters/Shining-Fates-logo.webp','/pokemon/boosters/Shining-Fates-symbol.webp'),
	('Vivid Voltage','Sword & Shield','2020-11-13','viv',185,18,203,1,0,'/pokemon/boosters/Vivid-Voltage-logo.webp','/pokemon/boosters/Vivid-Voltage-symbol.webp'),
	('Champion''s Path','Sword & Shield','2020-09-25','cpa',73,7,80,1,0,'/pokemon/boosters/Champions-Path-logo.webp','/pokemon/boosters/Champions-Path-symbol.webp'),
	('Darkness Ablaze','Sword & Shield','2020-08-14','daa',189,12,201,1,0,'/pokemon/boosters/Darkness-Ablaze-logo.webp','/pokemon/boosters/Darkness-Ablaze-symbol.webp'),
	('Rebel Clash','Sword & Shield','2020-05-01','rcl',192,17,209,1,0,'/pokemon/boosters/Rebel-Clash-logo.webp','/pokemon/boosters/Rebel-Clash-symbol.webp'),
	('Sword & Shield','Sword & Shield','2020-02-07','ssh',202,14,216,1,0,'/pokemon/boosters/Sword-Shield-logo.webp','/pokemon/boosters/Sword-Shield-symbol.webp'), 
	
	('Black Bolt','Scarlet & Violet','2025-07-18','blk',86,86,172,1,0,'/pokemon/boosters/Black-Bolt-logo.webp','/pokemon/boosters/Black-Bolt-symbol.webp'),
	('White Flare','Scarlet & Violet','2025-07-18','wht',86,87,173,1,0,'/pokemon/boosters/White-Flare-logo.webp','/pokemon/boosters/White-Flare-symbol.webp'),
	('Destined Rivals','Scarlet & Violet','2025-05-30','dri',182,62,244,1,0,'/pokemon/boosters/Destined-Rivals-logo.webp','/pokemon/boosters/Destined-Rivals-symbol.webp'),
	('Journey Together','Scarlet & Violet','2025-03-28','jtg',180,10,190,1,0,'/pokemon/boosters/Journey-Together-logo.webp','/pokemon/boosters/Journey-Together-symbol.webp'),
	('Prismatic Evolutions','Scarlet & Violet','2025-01-17','pre',131,49,180,1,0,'/pokemon/boosters/Prismatic-Evolutions-logo.webp','/pokemon/boosters/Prismatic-Evolutions-symbol.webp'),
	('Surging Sparks','Scarlet & Violet','2024-11-08','srp',250,2,252,1,0,'/pokemon/boosters/Surging-Sparks-logo.webp','/pokemon/boosters/Surging-Sparks-symbol.webp'),
	('Stellar Crown','Scarlet & Violet','2024-09-13','scr',142,33,175,1,0,'/pokemon/boosters/Stellar-Crown-logo.webp','/pokemon/boosters/Stellar-Crown-symbol.webp'),
	('Shrouded Fable','Scarlet & Violet','2024-08-02','sfa',64,35,99,1,0,'/pokemon/boosters/Shrouded-Fable-logo.webp','/pokemon/boosters/Shrouded-Fable-symbol.webp'),
	('Twilight Masquerade','Scarlet & Violet','2024-05-24','twm',167,59,226,1,0,'/pokemon/boosters/Twilight-Masquerade-logo.webp','/pokemon/boosters/Twilight-Masquerade-symbol.webp'),
	('Temporal Forces','Scarlet & Violet','2024-02-22','tef',162,56,218,1,0,'/pokemon/boosters/Temporal-Forces-logo.webp','/pokemon/boosters/Temporal-Forces-symbol.webp'),
	('Paldean Fates','Scarlet & Violet','2024-01-26','paf',91,154,245,1,0,'/pokemon/boosters/Paldean-Fates-logo.webp','/pokemon/boosters/Paldean-Fates-symbol.webp'),
	('Paradox Rift','Scarlet & Violet','2023-11-03','par',182,84,266,1,0,'/pokemon/boosters/Paradox-Rift-logo.webp','/pokemon/boosters/Paradox-Rift-symbol.webp'),
	('151','Scarlet & Violet','2023-09-22','mew',165,42,207,1,0,'/pokemon/boosters/151-logo.webp','/pokemon/boosters/151-symbol.webp'),
	('Obsidian Flames','Scarlet & Violet','2023-08-11','obf',197,33,230,1,0,'/pokemon/boosters/Obsidian-Flames-logo.webp','/pokemon/boosters/Obsidian-Flames-symbol.webp'),
	('Paldea Evolved','Scarlet & Violet','2023-07-09','pal',193,86,279,1,0,'/pokemon/boosters/Paldea-Evolved-logo.webp','/pokemon/boosters/Paldea-Evolved-symbol.webp'),
	('Scarlet & Violet','Scarlet & Violet','2023-03-31','svi',198,60,258,1,0,'/pokemon/boosters/Scarlet-Violet-logo.webp','/pokemon/boosters/Scarlet-Violet-symbol.webp'), 
	
	('Chaos Rising','Mega Evolution','2026-05-22','cri',86,0,86,1,0,'/pokemon/boosters/Chaos-Rising-logo.webp','/pokemon/boosters/Chaos-Rising-symbol.webp'),
	('Perfect Order','Mega Evolution','2026-03-27','por',88,36,124,1,0,'/pokemon/boosters/Perfect-Order-logo.webp','/pokemon/boosters/Perfect-Order-symbol.webp'),
	('Ascended Heroes','Mega Evolution','2026-01-30','asc',217,78,295,1,0,'/pokemon/boosters/Ascended-Heroes-logo.webp','/pokemon/boosters/Ascended-Heroes-symbol.webp'),
	('Phantasmal Flames','Mega Evolution','2025-11-14','pfl',94,36,130,1,0,'/pokemon/boosters/Phantasmal-Flames-logo.webp','/pokemon/boosters/Phantasmal-Flames-symbol.webp'),
	('Mega Evolution','Mega Evolution','2025-09-26','meg',132,56,188,1,0,'/pokemon/boosters/Mega-Evolution-logo.webp','/pokemon/boosters/Mega-Evolution-symbol.webp'), 
	
	('Mega Evolution Promos','Black Star','2025-09-01','mep',79,0,79,1,0,'/pokemon/boosters/Mega-Evolution-Promos-logo.webp','/pokemon/boosters/Mega-Evolution-Promos-symbol.webp'),
	('Scarlet & Violet Promos','Black Star','2023-01-01','svp',225,0,225,1,0,'/pokemon/boosters/Scarlet-Violet-Promos-logo.webp','/pokemon/boosters/Scarlet-Violet-Promos-symbol.webp'),
	('Sword & Shield Promos','Black Star','2019-11-01','ssp',307,0,307,1,0,'/pokemon/boosters/Sword-Shield-Promos-logo.webp','/pokemon/boosters/Old-Promos-symbol.webp'),
	('Sun & Moon Promos','Black Star','2016-11-01','smp',248,0,248,1,0,'/pokemon/boosters/Sun-Moon-Promos-logo.webp','/pokemon/boosters/Old-Promos-symbol.webp'),
	('XY Promos','Black Star','2013-10-01','xyp',211,0,211,1,0,'/pokemon/boosters/XY-Promos-logo.webp','/pokemon/boosters/Old-Promos-symbol.webp'),
	('Black & White Promos','Black Star','2011-04-01','bwp',101,0,101,1,0,'/pokemon/boosters/Black-White-Promos-logo.webp','/pokemon/boosters/Old-Promos-symbol.webp'),
	('HeartGold & SoulSilver Promos','Black Star','2010-02-01','hsp',25,0,25,1,0,'/pokemon/boosters/HeartGold-SoulSilver-Promos-logo.webp','/pokemon/boosters/Old-Promos-symbol.webp'),
	('Diamond & Pearl Promos','Black Star','2007-05-01','dpp',56,0,56,1,0,'/pokemon/boosters/Diamond-Pearl-Promos-logo.webp','/pokemon/boosters/Old-Promos-symbol.webp'),
	('Nintendo Promos','Black Star','2003-10-01','np',40,0,40,1,0,'/pokemon/boosters/Nintendo-Promos-logo.webp','/pokemon/boosters/Old-Promos-symbol.webp'),
	('Wizards Promos','Black Star','1999-07-01','wp',54,0,54,1,0,'/pokemon/boosters/Wizards-Promos-logo.webp','/pokemon/boosters/Old-Promos-symbol.webp'),
	
	('McDonald''s 2011','McDonald''s Collection','2011-06-17','m11',12,0,12,1,0,'/pokemon/boosters/McDonalds-2011-logo.webp','/pokemon/boosters/McDonalds-2011-symbol.webp'),
	('McDonald''s 2012','McDonald''s Collection','2012-06-15','m12',12,0,12,1,0,'/pokemon/boosters/McDonalds-2012-logo.webp','/pokemon/boosters/McDonalds-2012-symbol.webp'),
	('McDonald''s 2013','McDonald''s Collection','2013-10-13','m13',12,0,12,1,0,'/pokemon/boosters/McDonalds-2013-logo.webp','/pokemon/boosters/McDonalds-2013-symbol.webp'),
	('McDonald''s 2014','McDonald''s Collection','2014-05-23','m14',12,0,12,1,0,'/pokemon/boosters/McDonalds-2014-logo.webp','/pokemon/boosters/McDonalds-2014-symbol.webp'),
	('McDonald''s 2015','McDonald''s Collection','2015-10-14','m15',12,0,12,1,0,'/pokemon/boosters/McDonalds-2015-logo.webp','/pokemon/boosters/McDonalds-2015-symbol.webp'),
	('McDonald''s 2016','McDonald''s Collection','2016-08-19','m16',12,0,12,1,0,'/pokemon/boosters/McDonalds-2016-logo.webp','/pokemon/boosters/McDonalds-2016-symbol.webp'),
	('McDonald''s 2017','McDonald''s Collection','2017-07-01','m17',12,0,12,1,0,'/pokemon/boosters/McDonalds-2017-logo.webp','/pokemon/boosters/McDonalds-2017-symbol.webp'),
	('McDonald''s 2018','McDonald''s Collection','2018-10-16','m18',12,0,12,1,0,'/pokemon/boosters/McDonalds-2018-logo.webp','/pokemon/boosters/McDonalds-2018-symbol.webp'),
	('McDonald''s 2019','McDonald''s Collection','2019-10-15','m19',12,0,12,1,0,'/pokemon/boosters/McDonalds-2019-logo.webp','/pokemon/boosters/McDonalds-2019-symbol.webp'),
	('McDonald''s 2021','McDonald''s Collection','2021-02-09','m21',25,0,25,1,0,'/pokemon/boosters/McDonalds-2021-logo.webp','/pokemon/boosters/McDonalds-2021-symbol.webp'),
	('McDonald''s 2022','McDonald''s Collection','2022-08-03','m22',15,0,15,1,0,'/pokemon/boosters/McDonalds-2022-logo.webp','/pokemon/boosters/McDonalds-2022-symbol.png'),
	('McDonald''s 2023','McDonald''s Collection','2023-07-27','m23',15,0,15,1,0,'/pokemon/boosters/McDonalds-2023-logo.webp','/pokemon/boosters/McDonalds-2023-symbol.webp'),
	('McDonald''s 2024','McDonald''s Collection','2024-10-04','m24',15,0,15,1,0,'/pokemon/boosters/McDonalds-2024-logo.webp','/pokemon/boosters/McDonalds-2024-symbol.webp'),
	('McDonald''s 2025','McDonald''s Collection','2025-01-21','m25',15,0,15,1,0,'/pokemon/boosters/McDonalds-2025-logo.webp','none'),
	
	('Trick or Trade 2022','Trick or Trade','2022-09-01','tt22',30,0,30,1,0,'/pokemon/boosters/Trick-Or-Trade-2022-logo.webp','none'),
	('Trick or Trade 2023','Trick or Trade','2023-09-01','tt23',30,0,30,1,0,'/pokemon/boosters/Trick-Or-Trade-2023-logo.webp','none'),
	('Trick or Trade 2024','Trick or Trade','2024-08-30','tt24',30,0,30,1,0,'/pokemon/boosters/Trick-Or-Trade-2024-logo.webp','none'),
	
	('POP 1','POP','2004-09-01','pop1',17,0,17,1,1,'/pokemon/boosters/POP-1-logo.webp','/pokemon/boosters/POP-1-symbol.webp'),
	('POP 2','POP','2005-08-01','pop2',17,0,17,1,1,'/pokemon/boosters/POP-2-logo.webp','/pokemon/boosters/POP-2-symbol.webp'),
	('POP 3','POP','2006-04-01','pop3',17,0,17,1,1,'/pokemon/boosters/POP-3-logo.webp','/pokemon/boosters/POP-3-symbol.webp'),
	('POP 4','POP','2006-08-01','pop4',17,0,17,1,1,'/pokemon/boosters/POP-4-logo.webp','/pokemon/boosters/POP-4-symbol.webp'),
	('POP 5','POP','2007-04-01','pop5',17,0,17,1,1,'/pokemon/boosters/POP-5-logo.webp','/pokemon/boosters/POP-5-symbol.webp'),
	('POP 6','POP','2007-09-01','pop6',17,0,17,1,1,'/pokemon/boosters/POP-6-logo.webp','/pokemon/boosters/POP-6-symbol.webp'),
	('POP 7','POP','2008-04-01','pop7',17,0,17,1,1,'/pokemon/boosters/POP-7-logo.webp','/pokemon/boosters/POP-7-symbol.webp'),
	('POP 8','POP','2008-09-01','pop8',17,0,17,1,1,'/pokemon/boosters/POP-8-logo.webp','/pokemon/boosters/POP-8-symbol.webp'),
	('POP 9','POP','2009-03-01','pop9',17,0,17,1,1,'/pokemon/boosters/POP-9-logo.webp','/pokemon/boosters/POP-9-symbol.webp'),
	
	('Play! 1','Play! Pokemon Prize Pack','2022-11-09','pps1',0,0,0,1,0,'/pokemon/boosters/Play-1-logo.png','none'),
	('Play! 2','Play! Pokemon Prize Pack','2023-01-19','pps2',0,0,0,1,0,'/pokemon/boosters/Play-2-logo.png','none'),
	('Play! 3','Play! Pokemon Prize Pack','2023-08-14','pps3',0,0,0,1,0,'/pokemon/boosters/Play-3-logo.png','none'),
	('Play! 4','Play! Pokemon Prize Pack','2024-02-14','pps4',0,0,0,1,0,'/pokemon/boosters/Play-4-logo.png','none'),
	('Play! 5','Play! Pokemon Prize Pack','2024-08-14','pps5',0,0,0,1,0,'/pokemon/boosters/Play-5-logo.png','none'),
	('Play! 6','Play! Pokemon Prize Pack','2025-02-14','pps6',0,0,0,1,0,'/pokemon/boosters/Play-6-logo.png','none'),
	('Play! 7','Play! Pokemon Prize Pack','2025-08-14','pps7',0,0,0,1,0,'/pokemon/boosters/Play-7-logo.png','none'),
	('Play! 8','Play! Pokemon Prize Pack','2025-08-14','pps8',0,0,0,1,0,'/pokemon/boosters/Play-8-logo.png','none'),
	
	('Pokemon Futsal','Miscellaneous','2020-09-11','fut20',5,0,5,1,0,'/pokemon/boosters/Pokemon-Futsal-logo.webp','/pokemon/boosters/Pokemon-Futsal-symbol.webp'),
	('Pokemon Rumble','Miscellaneous','2009-12-02','rm',16,0,16,1,0,'/pokemon/boosters/Pokemon-Rumble-logo.webp','/pokemon/boosters/Pokemon-Rumble-symbol.webp'),
	('Poke Card Creator Pack','Miscellaneous','2004-07-01','cc',0,0,0,1,0,'/pokemon/boosters/Poke-Card-Creator-Pack-logo.png','none'),
	('Best of Game','Miscellaneous','2002-12-01','best',0,0,0,1,0,'/pokemon/boosters/Best-Of-Game-logo.webp','/pokemon/boosters/Best-Of-Game-symbol.webp'),
	('Southern Islands','Miscellaneous','2001-07-31','sl',18,0,18,1,0,'/pokemon/boosters/Southern-Islands-logo.webp','/pokemon/boosters/Southern-Islands-symbol.webp')

GO

PRINT '*** adding to Card Table ***'
GO
INSERT INTO [dbo].[PokemonCard]
	(
		[ArtistID],[AbilityID],[BoosterID],[PokemonRuleID],[ElementTypeID],
		[Name],[BoosterNumber],[CardType],[Rarity],[WeaknessType],
		[ResistanceType],[WeaknessValue],[ResistanceValue],[RetreatCost],
		[Health],[Stage],[ImagePath],[Active]
	)
VALUES
		(5,'Cursed Blast','Shrouded Fable','none','psychic','Dusknoir',70,'Pokemon','Illustration Rare','dark','fighting',2,30,3,160,'Stage 2','/pokemon/cards/sfa/70.png',1),
		(1,'Boosted Evolution','Scarlet & Violet Promos','none','colorless','Eevee',173,'Pokemon','Illustration Rare','fighting','none',2,0,1,50,'Basic','/pokemon/cards/svp/173.png',1),
		(1,'none','Mega Evolution','Mega Evolution','fire','Mega Camerupt EX', 156,'Pokemon','Ultra Rare','water','none',2,0,4,340,'Stage 1','/pokemon/cards/meg/156.png',1),
		(1,'none','XY Promos','Pokemon-EX','colorless','Rayquaza EX', 69, 'Pokemon','Rare','electric','fighting',2,20,2,170,'Basic','/pokemon/cards/xyp/69.png',1),
		(1,'none','Astral Radiance','Pokemon V','dragon','Garchomp V',23,'Pokemon','Gallery','none','none',0,0,0,200,'Basic','/pokemon/cards/asr/gallery/23.png',1),
		(1,'none','Ancient Origins','Pokemon-EX','Fighting','Primal Groudon EX',97,'Pokemon','Full Art','grass','none',2,0,4,240,'Mega','/pokemon/cards/aor/97.png',1),
		(1,'none','Roaring Skies','Pokemon-EX','dragon','M Rayquaza EX',61,'Pokemon','Rare','fairy','none',2,0,2,230,'Mega','/pokemon/cards/ros/61.png',1),
		(1,'none','Roaring Skies','Pokemon-EX','dragon','M Latios EX',102,'Pokemon','Full Art','fairy','none',2,0,0,220,'Mega','/pokemon/cards/ros/102.png',1),
		(1,'none','Flashfire','Pokemon-EX','dragon','M Charizard EX',108,'Pokemon','Secret Rare','fairy','none',2,0,3,230,'Mega','/pokemon/cards/flf/108.png',1),
		(1,'none','Scarlet & Violet Promos','none','fire','Victini',208,'Pokemon','Illustration Rare','water','none',2,0,1,80,'Basic','/pokemon/cards/svp/208.png',1),
		(1,'none','White Flare','none','psychic','Woobat',119,'Pokemon','Illustration Rare','electric','fighting',2,30,1,60,'Basic','/pokemon/cards/wht/119.png',1),	
		(1,'none','Shrouded Fable','none','fire','Houndoom',66,'Pokemon','Illustration Rare','water','none',2,0,2,120,'Stage 1','/pokemon/cards/sfa/66.png',1),
		(1,'none','Scarlet & Violet Promos','none','steel','Kingambit',130,'Pokemon','Illustration Rare','fire','grass',2,30,4,180,'Stage 2','/pokemon/cards/svp/130.png',1),
		(1,'Skyscraper','Crown Zenith','Pokemon VMAX','dragon','Duraludon VMAX',104,'Pokemon','Full Art','none','none',0,0,3,330,'VMAX','/pokemon/cards/crz/base/104.png',1),
		(1,'none','Journey Together','none','dragon','N''s Reshiram',167,'Pokemon','Illustration Rare','none','none',0,0,2,130,'Basic','/pokemon/cards/jtg/167.png',1),
		(1,'none','White Flare','none','dark','Scraggy',138,'Pokemon','Illustration Rare','grass','none',2,0,1,70,'Basic','/pokemon/cards/wht/138.png',1),
		(1,'none','Mega Evolution','Mega Evolution','fighting','Mega Lucario EX',77,'Pokemon','Rare','psychic','none',2,0,2,340,'Stage 1','/pokemon/cards/meg/77.png',1),
		(1,'none','Paldea Evolved','none','fighting','Nacli',220,'Pokemon','Illustration Rare','grass','none',2,0,3,70,'Basic','/pokemon/cards/pal/220.png',1),
		(1,'none','BREAKthrough','Pokemon-EX','psychic','Mewtwo Ex',163,'Pokemon','Secret Rare','psychic','none',2,0,2,170,'Basic','/pokemon/cards/bkt/163.png',1),
		(1,'none','Twilight Masquerade','Pokemon-EX','electric','Luxray EX',195,'Pokemon','Ultra Rare','fighting','none',2,0,1,310,'Stage 2','/pokemon/cards/twm/195.png',1),
		(1,'none','Shrouded Fable','none','water','Horsea',67,'Pokemon','Illustration Rare','electric','none',2,0,1,60,'Basic','/pokemon/cards/sfa/67.png',1),
		(1,'none','Surging Sparks','none','psychic','Latios',203,'Pokemon','Illustration Rare','dark','fighting',2,30,2,120,'Basic','/pokemon/cards/srp/203.png',1),
		(1,'none','Destined Rivals','none','water','Clamperl',195,'Pokemon','Illustration Rare','electric','none',2,0,2,60,'Basic','/pokemon/cards/dri/195.png',1),
		(1,'Moon Cleave Star','Crown Zenith','Pokemon VSTAR','dark','Hisuian Samurott VSTAR',52,'Pokemon','Gallery','grass','none',2,0,2,270,'VSTAR','/pokemon/cards/crz/gallery/52.png',1),
		(1,'Sun Energy','Crown Zenith','none','fighting','Solrock',15,'Pokemon','Gallery','grass','none',2,0,1,90,'Basic','/pokemon/cards/crz/gallery/15.png',1),
		(1,'none','Temporal Forces','none','steel','Metagross',178,'Pokemon','Illustration Rare','fire','grass',2,30,3,180,'Stage 2','/pokemon/cards/tef/178.png',1),
		(1,'Witch''s Domain','Crown Zenith','Pokemon VMAX','psychic','Hatterene VMAX',47,'Pokemon','Gallery','dark','fighting',2,30,2,320,'VMAX','/pokemon/cards/crz/gallery/47.png',1),
		(1,'Star Guardian','Crown Zenith','Pokemon VSTAR','colorless','Regigigas VSTAR',55,'Pokemon','Gallery','fighting','none',2,0,4,300,'VSTAR','/pokemon/cards/crz/gallery/55.png',1),
		(1,'Team Rocket''s Archer','Destined Rivals','Supporter','colorless','Team Rocket''s Archer',223,'Trainer','Ultra Rare','none','none',0,0,0,0,'Supporter','/pokemon/cards/dri/223.png',1),
		(1,'Team Rocket''s Ariana','Destined Rivals','Supporter','colorless','Team Rocket''s Ariana',224,'Trainer','Ultra Rare','none','none',0,0,0,0,'Supporter','/pokemon/cards/dri/224.png',1)
GO

PRINT '*** adding to Card Move Table ***'
GO
INSERT INTO [dbo].[CardMove]
	([PokemonCardID],[MoveID])
VALUES
	(1,1),
	(2,2),
	(3,3),
	(3,4),
	(4,5),
	(4,6),
	(5,7),
	(5,8),
	(6,9),
	(7,10),
	(8,11),
	(9,12),
	(10,13),
	(11,14),
	(12,15),
	(12,16),
	(13,17),
	(13,18),
	(14,19),
	(15,20),
	(15,21),
	(16,22),
	(16,23),
	(17,24),
	(17,25),
	(18,26),
	(18,27),
	(19,28),
	(19,29),
	(20,30),
	(20,31),
	(21,32),
	(21,33),
	(22,34),
	(22,35),
	(23,36),
	(24,37),
	(25,38),
	(26,39),
	(26,40),
	(27,41),
	(28,42)
GO

PRINT '*** adding to Card Alternate Art Table ***'
GO
INSERT INTO [dbo].[CardAlternateArt]
	([PokemonCardID],[AlternateArtID])
VALUES
	(1,'none'),
	(2,'none'),
	(3,'none'),
	(4,'none'),
	(5,'none'),
	(6,'none'),
	(7,'none'),
	(8,'none'),
	(9,'none'),
	(10,'none'),
	(11,'none'),
	(12,'none'),
	(13,'none'),
	(14,'none'),
	(15,'none'),
	(16,'none'),
	(17,'none'),
	(18,'none'),
	(19,'none'),
	(20,'none'),
	(21,'none'),
	(22,'none'),
	(23,'none'),
	(24,'none'),
	(25,'none'),
	(26,'none'),
	(27,'none'),
	(28,'none'),
	(29,'none'),
	(30,'none')
GO

PRINT '*** adding to Collection Table ***'
GO
INSERT INTO [dbo].[Collection]
	([UserID],[CollectionTypeID],[Name],[Description])
VALUES
	(10000,'user','My Cards','A list of all my cards.'),
	(10000,'Deck','My First Deck','My first deck.'),
	(10001,'user','My Cards','A list of all my cards.'),
	(10002,'user','My Cards','A list of all my cards.'),
	(10003,'user','My Cards','A list of all my cards.'),
	(10004,'user','My Cards','A list of all my cards.'),
	(10000,'Wishlist','Wishlist','List of cards I want to get.'),
	(10001,'Wishlist','Wishlist','List of cards I want to get.'),
	(10002,'Wishlist','Wishlist','List of cards I want to get.'),
	(10003,'Wishlist','Wishlist','List of cards I want to get.'),
	(10004,'Wishlist','Wishlist','List of cards I want to get.'),
	(10000,'Favorites','Favorites','List of my favorite cards.'),
	(10001,'Favorites','Favorites','List of my favorite cards.'),
	(10002,'Favorites','Favorites','List of my favorite cards.'),
	(10003,'Favorites','Favorites','List of my favorite cards.'),
	(10004,'Favorites','Favorites','List of my favorite cards.')
GO

PRINT '*** adding to Collection Card Table ***'
GO
INSERT INTO [dbo].[CollectionCard]
	([PokemonCardID],[CollectionID],[Quantity],[Owned])
VALUES
	(1,1,1,1),
	(2,1,2,1),
	(13,1,1,1),
	(1,2,1,1),
	(21,2,1,1),
	(12,2,4,1),
	(22,2,3,1)
GO

PRINT '*** adding to Collection Element Table ***'
GO
INSERT INTO [dbo].[CollectionElement]
	([CollectionID],[ElementTypeID])
VALUES
	(2,"fire")
GO